### ISSUE TITLE
Wait for async action

### ISSUE THREAD

**Issue by fkrauthan** [acdlite/flummox#105]
Is there any programmatic way to wait for a async action to finish? My use case is I have a server method that invokes a action and needs to wait until that action is finished before proceeding.

**Comment by acdlite** [comment]
Since the return value of an async action is a promise, you can use `.then()`:

```js
myActions.someAsyncAction().then(result => {...});
```

Or if you're using async-await:

```js
async () => {
  const result = await myActions.someAsyncAction();
  ...
}();
```

Hope that helps!

**Comment by fkrauthan** [comment]
Perfect that brings my goal a react app that works without javascript on client site a huge step closer.
