### ISSUE TITLE
FluxComponent and React 0.13 Rationale

### ISSUE THREAD

**Issue by dchambers** [acdlite/flummox#106]
First off let me state that I'm knew to both React and Flummox, so apologies for any misunderstandings...

The [React integration guide](https://github.com/acdlite/flummox/blob/master/docs/react-integration.md) states:

> **In v3.0, FluxComponent requires React 0.13. If you're still on React 0.12, keep using Flummox 2.x until you're able to upgrade.**

which seems to indicate that we should still be using `FluxComponent` with React 0.13, but when I tried to implement a very simple example using the `latest` versions of React and Flummox (including the use of `FluxComponent`) I got these errors:

```bash
Warning: withContext is deprecated and will be removed in a future version. Use a wrapper
component with getChildContext instead.
Warning: owner-based and parent-based contexts differ (values: `[object Object]` vs
`undefined`) for key (flux) while mounting FluxComponent (see: http://fb.me/react-context-by-parent)
```

I found that following the provided recommendation and adding a `getChildContext()` method initially seemed to make things worse, as it appeared to be clashing with `FluxComponent`.

Instead, by following the [see link](http://fb.me/react-context-by-parent) it provides, I discovered that contexts are now being handled differently than before, and this made wonder whether `FluxComponent` was really even needed anymore. So, by getting rid of `FluxComponent` I was able to get rid of both warnings, yet was still able to have an inner component that had access to the parent context.

This additionally simplified things by allowing the parent component to construct the `Flux` instance rather than constructing code, which was more natural for my example, and by getting rid of the need to wrap `React.render()` with a `React.withContext()` invocation.

Given all of this, are there benefits to keeping `FluxComponent` around that I'm not yet aware of? If so, is there a way to continue using it but without the warning messages?

**Comment by acdlite** [comment]
Could you post a snippet please? I have a feeling you're getting a false negative, but I can't be sure unless I see your source code.

You shouldn't be using `React.withContext()` anymore, since that is deprecated.

The recommended way to add Flux to context using FluxComponent is

```js
<FluxComponent
  flux={flux}
  render={storeState => <Child {...storeState} />}
/>
```

As a last resort, you can circumvent warning messages by using `getChildContext()` yourself. FluxComponent is still useful for its `connectToStores()` functionality.

**Comment by dchambers** [comment]
Hi @acdlite,

Thanks for coming back to me. I'm now really confused what's going on since I can no longer can find any documentation mentioning `React.withContext()`, so I'm not actually sure how or why I ended up using it.

Additionally, although I can replicate this message:

```
Warning: withContext is deprecated and will be removed in a future version. Use a wrapper
component with getChildContext instead.
```

by using `React.withContext()`, I can no longer replicate this message:

```
Warning: owner-based and parent-based contexts differ (values: `[object Object]` vs
`undefined`) for key (flux) while mounting FluxComponent (see: http://fb.me/react-context-by-parent)
```

and am now able to use either `getChildContext()` or `<FluxComponent
  flux={flux}/>`, so am confused about what I was doing differently when I originally raised this bug. Finally, it's now patently obvious to me that `<FluxComponent/>` also makes depending on stores much simpler!

So ... I'm closing this issue as it seems to have been caused only by something weird I was doing, and I'm not even sure what documentation I read since everything I can now find seems up to date and correct.
