### ISSUE TITLE
How to use waitFor method of Dispatcher?

### ISSUE THREAD

**Issue by bjrmatos** [acdlite/flummox#110]
Are there any example of this?

Maybe a good one will be the flux's [chat app](https://github.com/facebook/flux/tree/master/examples/flux-chat/) (it uses `waitFor`) rewritten with flummox. :)

**Comment by acdlite** [comment]
Here ya go :) https://github.com/acdlite/flummox/blob/master/docs/api/Store.md#waitfor

Yeah, better examples are sorely needed.

**Comment by soda29** [comment]
Link is not working, can you provide a new one?

**Comment by acdlite** [comment]
Here ya go: https://github.com/acdlite/flummox/blob/master/docs/docs/api/store.md#waitfor
