### ISSUE TITLE
Idiomatic app based on Flummox

### ISSUE THREAD

**Issue by netgusto** [acdlite/flummox#114]
Hello,

I built an idiomatic app based on React, Flummox, Immutable.js and Webpack : https://github.com/netgusto/IdiomaticReact
I feel like it could help developers to understand how to build an app using Flummox and consors.

If you ever find the time, I would be very glad if you could review it; the aim is to be as simple and idiomatic as possible.

Thanks !

**Comment by nelix** [comment]
I'll go raise some issues on the project with feedback

**Comment by tcoopman** [comment]
I've already put my comments in https://github.com/rackt/react-router/issues/997 
Maybe should have put them in the project itself.

**Comment by acdlite** [comment]
Great project, @netgusto! One suggestion I'd make is to move the topmost FluxComponent (https://github.com/netgusto/IdiomaticReact/blob/master/src/scripts/components/App.js#L19) up to the root (https://github.com/netgusto/IdiomaticReact/blob/master/src/scripts/components/main.js#L31), like so:

```js
React.render(
  <FluxComponent flux={flux}>
    <Handler />
  </FluxComponent>,
  document.getElementById('app')
);
```
