### ISSUE TITLE
Store setState doesn't accept a callback

### ISSUE THREAD

**Issue by fczuardi** [acdlite/flummox#115]
In the documentation for the setState method of the Store class at https://github.com/acdlite/flummox/blob/master/docs/api/Store.md#setstate it says that you can pass a callback as a second parameter.

The implementation howerver doesn't look like it is receiving and triggering this callback at all, see https://github.com/acdlite/flummox/blob/master/src/Store.js#L26

**Comment by acdlite** [comment]
Huh, not sure how that slipped into the docs. That's not meant to be a feature. I will remove it. Thanks!

(If you need this functionality, please open a separate issue explaining why.)

**Comment by fczuardi** [comment]
Other than simply React's Component API parity, the usecase I encountered for needing this feature was a store that updates a localStorage value upon state change. What would be the proper way of doing that? Have the store to listen to it's own change events? Feels a little weird IMHO…

**Comment by acdlite** [comment]
Hmm, why do you need a callback to do this?

```js
handleSomeAction(foo) {
  this.setState({ foo });
  localStorage.setItem('foo', foo);
}
```

Btw, I'm not necessarily opposed to adding a callback as a feature. I just want to make sure there's a valid use case. In React, it makes sense because the callback is called after the component has re-rendered. The analogous concept in Flummox would be to call a callback after the `change` event has fired. Is that really all that useful?

**Comment by fczuardi** [comment]
Well, adding this to the Store constructor:

```javascript
        this.addListener('change', function(){
            console.log('I have changed', this.state);
        });
```
Works for this "save the latest value in the localStorage" case, so I can leave without React's API parity :) The listener gets called on every state change and not just after a particular kind like with callbacks, but doesn't look like a big issue at the moment.
