### ISSUE TITLE
FluxComponent: context.flux is undefined 

### ISSUE THREAD

**Issue by nd0ut** [acdlite/flummox#118]
AppView.render
```javascript
      <FluxComponent flux={this.flux}>
        <div className="app-container">
          <HeaderView />
          <SidebarView />
          <TimelineView />
        </div>
      </FluxComponent>
```
TimelineView.render
```javascript
      <FluxComponent>
        <div className="timeline">
          <TimelineToolbar />
          <TimelineScroller />
        </div>
      </FluxComponent>
```
I get error at second FluxComponent:
```
fluxMixin: Could not find Flux instance. Ensure that your component has either `this.context.flux` or `this.props.flux`.
```
context:
```javascript
this.context
Object {flux: undefined}
```
What's wrong?

**Comment by acdlite** [comment]
First, make sure `this.flux` in your AppView is actually defined. Unless you assigned it yourself (or are using fluxMixin) that doesn't look right.

If that's not the problem, then I think this has to do with the fact that contexts in React are (until 0.14) owner-based, not context-based. This leads to issues sometimes with directly-nested FluxComponents. For now, you should be able to fix by using the render prop:

```js
<FluxComponent flux={this.flux} render={() =>{
  <div className="app-container">
    <HeaderView />
    <SidebarView />
    <TimelineView />
  </div>
}}/>
```

Better documentation about contexts is forthcoming.

**Comment by nd0ut** [comment]
@acdlite thanks. Now it magically works with render overriding. Although I've tried it before but with no luck.

**Comment by acdlite** [comment]
Yes, sorry for the frustration. Context is weird. I think it'll get much better once it switches to parent-based in React 0.14.
