### ISSUE TITLE
ES5 examples?

### ISSUE THREAD

**Issue by sahat** [acdlite/flummox#120]
Hey @acdlite,

Do you have any plans to add ES5 examples to the http://acdlite.github.io/flummox/guides/quick-start? Perhaps using a tab interface or radio button toggle between ES5 and ES6.

Meanwhile, how would the following code look in ES5?

```js
import { Actions } from 'flummox';

class MessageActions extends Actions {

  createMessage(messageContent) {
    return {
      content: messageContent,
      date: Date.now(),
    };
  }

}
```

Thanks.

**Comment by martintietz** [comment]
You can use [babel's online transpiler](http://babeljs.io/repl/) to transpile code between ES5 and ES6.

**Comment by sahat** [comment]
@martintietz Thanks, but I am not interested in transpiling just to get things to work. I like ES5 syntax and plan to use it for the forseeable future. For instance, this transpiled code is hardly readable and doesn't translate 1:1 to ES5:

```js
"use strict";

var _createClass = (function () { function defineProperties(target, props) { for (var key in props) { var prop = props[key]; prop.configurable = true; if (prop.value) prop.writable = true; } Object.defineProperties(target, props); } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

var _inherits = function (subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) subClass.__proto__ = superClass; };

var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };

var Actions = require("flummox").Actions;

var MessageActions = (function (_Actions) {
  function MessageActions() {
    _classCallCheck(this, MessageActions);

    if (_Actions != null) {
      _Actions.apply(this, arguments);
    }
  }

  _inherits(MessageActions, _Actions);

  _createClass(MessageActions, {
    createMessage: {
      value: function createMessage(messageContent) {
        return {
          content: messageContent,
          date: Date.now() };
      }
    }
  });

  return MessageActions;
})(Actions);
```

In any case I was able to convert it to ES5 syntax with a little trial and error.

**Comment by acdlite** [comment]
ES5 support should get better in the next version, where you'll be able to pass plain JavaScript objects to `#createStore()` and `#createActions()`

**Comment by acdlite** [comment]
Right now it's supported, just not as convenient as with ES6 classes.

**Comment by sloria** [comment]
+1 to ES5 examples. Babel is not a feasible option for everyone, esp. if you want to support older browsers (ES6 classes, for example, [are only supported in IE > 10](http://babeljs.io/docs/usage/caveats/)). @acdlite Are there plans to document ES5 examples?

**Comment by sloria** [comment]
Related question: does prototypical inheritance with Flummox's classes? I often use the following two functions as "sugar" for getting ES6-style classes in ES5.

```js
function defclass(prototype) {
    var constructor = prototype.hasOwnProperty('constructor') ? prototype.constructor : function() {};
    constructor.prototype = prototype;
    return constructor;
}

function extend(cls, sub) {
    var prototype = Object.create(cls.prototype);
    for (var key in sub) { prototype[key] = sub[key]; }
    prototype.super = cls.prototype;
    return defclass(prototype);
}
```

As long as prototypical inheritance works in Flummox, then one could use the above functions like so:

```js
var Actions = require('flummox').Actions;

var MessageActions = extend(Actions, {
    createMessage: function(messageContent) {
        return {
            content: messageContent,
            date: Date.now()
        }
    }
});
```

Haven't gotten to trying this out in a real app yet, but it seems like this should be possible.

**Comment by acdlite** [comment]
Yes prototypical inheritance works. And Babel should work in IE if you enable "loose" mode (which Flummox does). Need to set up browser tests to confirm.

**Comment by acdlite** [comment]
@sloria This may be helpful re: Babel browser compatibility http://babeljs.io/docs/usage/caveats/

**Comment by sloria** [comment]
@acdlite I linked to that page in my previous comment to point out that certain features--such as classes--are not supported on older versions of IE, which is why it'd be great to see examples in ES5.

**Comment by acdlite** [comment]
Haha totally missed that. But unless I'm misinterpreting it, classes *are* supported down to IE 8 if you use loose mode. Also, React's JSX compiler supports a subset of ES6 features, including classes, so that's another option.

Agree that ES5 examples would be nice. On the todo list.

**Comment by bjrmatos** [comment]
I'm a little confused, i've found in docs that flux.createActions now supports a plain object to create an action, but nothing about the same for stores. Am i missing something? Or that is still not supported for stores?

**Comment by acdlite** [comment]
No plain object stores because you really need a constructor, whereas actions you (usually) can get away without one. I don't want to invent a special API specifically for this use case since most people can (if they're not using Babel) use React's JSX Harmony transform or one of the many JS inheritance libraries that exist.

**Comment by henit** [comment]
+1 to clean ES5 examples

**Comment by mjbellantoni** [comment]
+1

**Comment by chadly** [comment]
:+1: for a nicer es5 story.

I'm trying to introduce my team to flux & react and I really like the concepts behind Flummox but trying to also introduce es6 at the same time might freak some of them out.

Would it not work to have helper functions similar to react's `createClass` function? e.g.

```js
Store.createClass({
  init: function() {
  }
});
```

with the `init` function taking the place of the constructor.

**Comment by gaearon** [comment]
>Would it not work to have helper functions similar to react's createClass function? e.g.

You are already able to do this via tiny wrappers over Flummox's stores. On the other hand, adding this to the library means maintaining two different ways of doing things. I'd rather see Flummox not go that way.

It's not that I think classes are super-great (I prefer functional approach where possible), but the language already has a way of doing classes, and it seems wrong to introduce some alternative way for it today.

In fact, ES6 classes are totally consumable from ES5:

```js
var Store = require('flummox').Store;

function MyStore(flux) {
  Store.call(this, flux);
  // This is your constructor
}

MyStore.prototype = Object.create(Store.prototype);

MyStore.prototype.handleSomeAction = function() {
  // write your handlers like this!
}

module.exports = MyStore;
```
