### ISSUE TITLE
Errors in handler action aren't intercepted

### ISSUE THREAD

**Issue by MrEfrem** [acdlite/flummox#126]
```
export default class StargazersStore extends Store {

  constructor(flux) {
    super();

    let stargazerActionIds = flux.getActionIds('stargazers');

    this.register(stargazerActionIds.getStargazersByRepo, this.handleGetStargazersByRepo);
    ...
  }

  handleGetStargazersByRepo({ owner, repo, stargazers }) {
    throw new Error('test');
  ...
```

There shall be 'test' error, however receive an error already from react:
```
Invariant Violation: StargazerGridView.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

**Comment by acdlite** [comment]
This should be fixed in the latest version of Flummox. If not, let me know and I'll re-open.

**Comment by MrEfrem** [comment]
On the server the same error that didn't exchange.
On the client:
```
Uncaught (in promise) Error: Test {stack: (...), message: "Test"}
invariant.js:42 
Uncaught (in promise) Error: Invariant Violation: StargazerGridView.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object. {framesToPop: 1, stack: (...), message: "Invariant Violation: StargazerGridView.render(): A…undefined, an array or some other invalid object."}
```

**Comment by acdlite** [comment]
`A valid ReactComponent must be returned` is thrown by React when a non-renderable value is returned from `render()`. I doubt this has anything to do with Flummox, but if you post some example code somewhere, perhaps I can take a look :)

**Comment by MrEfrem** [comment]
Your old example:
https://github.com/MrEfrem/flummox-isomorphic-demo
Add 
```
 throw new Error('test');
```
in handleGetStargazersByRepo
https://github.com/MrEfrem/flummox-isomorphic-demo/blob/master/src/shared/stores/StargazerStore.js

Unless this error shan't be processed standard handlerError in koa?
And to stop further execution, having returned the http 500 Internal Server Error code?

And occurs, but in stdout nodejs 
```
Invariant Violation: StargazerGridView.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```
instead of 
Test...

**Comment by acdlite** [comment]
This line is incorrect: https://github.com/MrEfrem/flummox-isomorphic-demo/blob/master/src/shared/components/StargazerGridView.js#L13

It should be wrapped in a span or div tag. (Not your fault — I wrote this originally, but didn't catch the error.)

**Comment by acdlite** [comment]
Also, if you update Flummox in that project to 3.5.0, the error will be thrown properly. (However, because it's inside a promise, you will not see the error server-side unless you use the error event of the Flux class. In the browser, Chrome/Firefox will warn you.)

**Comment by MrEfrem** [comment]
Yes I probably up to the end didn't deal with promises.
Locally I was updated already to 3.5. Thanks for the help.

**Comment by acdlite** [comment]
No problem! Let me know if you need any more help. Promises (especially error handling inside promises) can be really tricky.
