### ISSUE TITLE
How to fetch docs by path? (docs sample app)

### ISSUE THREAD

**Issue by Snegostoop** [acdlite/flummox#128]
Hi, thank you for your work. I'm building an isomorphic app with react-router and flummox and trying to figure out how to structure it with your Docs example. If I understood properly, on the first load you pre-fetch all the articles (https://github.com/acdlite/flummox/blob/master/docs/src/shared/components/AppHandler.js#L16)
and then you load one of them into the Doc component depending on the path (https://github.com/acdlite/flummox/blob/master/docs/src/shared/components/DocHandler.js#L36) (holding all of them in the DocStore)

My question is how would you handle article fetching in case when you have many articles so loading them all at once is not an option. I see you have an action for this purpose (https://github.com/acdlite/flummox/blob/master/docs/src/shared/actions/DocActions.js#L6) but you don't use it in the app.
As I understand, I need to fire getDoc(path) action somewhere in DocHandler, after the path is received. Please suggest how would you handle it. Thanks.

**Comment by acdlite** [comment]
I'll update DocHandler.

**Comment by acdlite** [comment]
Here ya go! Hope that helps. https://github.com/acdlite/flummox/blob/master/docs/src/shared/components/DocHandler.js#L15-L23

**Comment by Snegostoop** [comment]
Thanks!
