### ISSUE TITLE
Keeping track of async issues.

### ISSUE THREAD

**Issue by jorgenfb** [acdlite/flummox#130]
I am trying to do optimistic updates in one of my stores. How do I keep track of which actions fails/succeeds if there are multiple ongoing actions at the same time?

My store has an array of things. I have an action to create a new thing which sends the create command to my server. In my store I add the thing to the store's array when the action begins. If I add two things at the same time, and one of them fails. There is no way of figuring out which of the requests failed. When the action fails I need to remove the thing (added optimistically) from my store's array. And when the actions succeeds I need to update the thing with the latest data from the server.

**Comment by acdlite** [comment]
In the upcoming 4.0 release, every action handler now receives the entire dispatcher payload as the final parameter. In the case of async actions, this includes a dispatch id to enable fine-grained optimistic updates.

npm install flummox@4.0.0-alpha to try it out.

**Comment by airwin** [comment]
Nice feature! Expecting 4.0.

**Comment by jorgenfb** [comment]
Great! Exactly what I needed!

Thank you!
