### ISSUE TITLE
How to handle errors in ActionCreator?

### ISSUE THREAD

**Issue by vesparny** [acdlite/flummox#14]
While getting data from server, I'm used to fire an SUCCESS action if the call succeed, and a FAILURE action if it doesn't.
How can I deal with errors with flummox?

**Comment by acdlite** [comment]
I've gone back and forth about whether or not Flummox should have a built-in solution for this. Fluxy automatically creates SUCCESS and FAILURE actions, but that creates its own set of problems IMO.

Here's one way you could do it now:

```js

class MyActions extends Actions {
  
  async getThingFromServer() {
    try {
      let thing = await serverRequest();
      this.getThingFromServerSuccess(thing);
    } catch(e) {
      this.getThingFromServerSucess(e);
    }
  }

  getThingFromServerSuccess(thing) {
    return thing;
  }

  getThingFromServerFailure(e) {
    return e;
  }
  
}

```

Do you have any suggestions for how Flummox could make this easier/better?

**Comment by vesparny** [comment]
yes this sounds great for me. Probably I'll end up putting **getThingFromServer** inside a **WebApiUtils**.
Thanks

**Comment by tomusher** [comment]
Sorry to reopen this - I'm enjoying using Flummox at the moment but am running in to this same issue.

Your proposed solution seems fine but is already getting a bit unwieldy when I need to deal with multiple actions, each with started, success and failure states.

I'd like to see something along the lines of:
```
 async getThingFromServer() {
    this.dispatch('some data', 'STARTED');
    try {
      let thing = await serverRequest();
      this.dispatch(thing, 'SUCCESS');
    } catch(e) {
      this.dispatch(e, 'FAILURE')
    }
  }
```
and a way of registering for those actions:
```
this.register(actionIds.getThingFromServer, this.onStartedLoadThing, ['STARTED']);
```

I'm not really aware of the problems this could create like you suggested though...

**Comment by acdlite** [comment]
@tomusher I hear ya. I want to make sure we get this right and pick the best possible solution.

First note that it's undocumented, but actions already can do `this.dispatch(constant, body)` if they like. The Flux instance also has full access to the dispatcher, so there's always that option. But we need something better.

I actually don't mind your proposed solution, but it got me thinking: we're already using promises, and promises already have an interface for registering `success` and `failure` handlers. Instead of solving this on the action side, by wrapping everything in a try-catch block and manually dispatching, we can handle this purely on the store side by adding a new method `registerAsync(action, begin, success, failure)`. I think this would be a more straightforward, simpler approach.

How does that sound?

**Comment by vesparny** [comment]
Honestly I felt comfortable using the method you proposed in the firs comment of this thread.
I think keeping that library as simple as possible would be its power.

**Comment by tomusher** [comment]
@acdlite That sounds like a more elegant way of doing it, definitely. I'm not entirely clear on how it would work in practice (how would actions trigger success/failure) but it would definitely make things simpler.

@vesparny There's definitely something to be said for simplicity, but already I've ended up with something like:
```
async loadNodes() {
    this.loadNodesStarted();
   try {
        // do some work
        this.loadNodesSuccess();
    } catch(e) {
        this.loadNodesFailed(e);
    }
}

loadNodeStarted() {
    // ...
}

loadNodeSuccess() {
    // ...
}

loadNodeFailed() {
    // ...
}
// ... repeat a few times for different async functions
```
which seems like a lot of boilerplate that it would be nice if the framework could handle.
I'd be interested to know how you're handling this now; perhaps I need to rethink my approach?

**Comment by acdlite** [comment]
@vesparny That was my initial instinct, too, but this is such a common pattern that it's at least worth considering how we can solve it. A minimal API is certainly one of the goals of Flummox, but so is reducing boilerplate.

If the tradeoff is adding a single new method (`registerAsync`) in exchange for significantly reduced boilerplate (as illustrated by @tomusher's previous comment), I think that's a good tradeoff.

**Comment by vesparny** [comment]
@tomusher what you did is exactly what I did too :) It doesn't bother me that much.
Anyway probably you are right because something that reduces boilerplate is definitely something clever.

**Comment by tomusher** [comment]
@acdlite Thanks for adding support for this, I've had a play and it seems to work really well!

**Comment by acdlite** [comment]
@tomusher Great! Thanks for your PR.
