### ISSUE TITLE
'undefined is not a function' with jquery promise

### ISSUE THREAD

**Issue by tko** [acdlite/flummox#145]
I have a pretty simple Action
```javascript
class MyActions extends Actions {
  test() {
    return $.ajax({..}).success(..).fail(..).promise();
  }
}
```
Everything seems to be working, but flummox keeps logging errors in console:
```
Flux.js:197 - Uncaught TypeError: undefined is not a function

   })['catch'](function (error) {
```
in `dispatchAsync`

**Comment by acdlite** [comment]
Hi! jQuery "promises" are not true promises, as they are not [Promises/A+](https://promisesaplus.com/) compliant. For example, they do not a have a `.catch()` method, which Flummox requires.

You can wrap jQuery "promise" in a real promise like so:

```js
Promise.resolve($.ajax({...}));
```

where `Promise` is any Promises/A++ library. If you're using Babel's polyfill, you're all set. Just use the global `Promise` object. Other options include [bluebird](https://github.com/petkaantonov/bluebird), [when](https://github.com/cujojs/when), and [es6-promise](https://github.com/jakearchibald/es6-promise).

Hope that helps!
