### ISSUE TITLE
FluxComponent having a child with a ref is dangerous

### ISSUE THREAD

**Issue by tko** [acdlite/flummox#147]
Not sure about implications but that's what React is warning about:
> Warning: You are calling cloneWithProps() on a child with a ref. This is dangerous because you're creating a new child which will not be added as a ref to its parent.

```javascript
render() {
  return (
    <FluxComponent connectToStores='test'>
      <Test ref="test" />
    </FluxComponent>
  );
}
```

Somewhat related to #45 maybe.

**Comment by acdlite** [comment]
Use a ref callback instead. https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute

**Comment by soda29** [comment]
How can this be achieved with a ref callback? code in the ref of Test does not get excecuted (it does with a ref in the FluxComponent.

**Comment by chrisforrette** [comment]
I'd love to know specifics around this as well— @soda29 or @tko did you find a solution?

**Comment by ai** [comment]
By some reason, `ref` callback in `FluxComponent` do not executed? But when I put `ref` to other node, everything works fine.

@acdlite can you provide some example maybe?
