### ISSUE TITLE
Isomorphic rendering error on http://acdlite.github.io/flummox

### ISSUE THREAD

**Issue by happypoulp** [acdlite/flummox#151]
Hi,

When opening the JS console on http://acdlite.github.io/flummox  we can see this message:

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
```
 (client) class="language-js"><span class="token k
 (server) class="language-js">const flux = new Flu
```

Is it just because of the syntax highlighting of the JS code (which would not be done server-side) or is it more tricky?

Thanks.

**Comment by acdlite** [comment]
Yeah, this is because Prism doesn't work server-side. If there's a better syntax highlighter that supports JSX we can switch to using that one.

**Comment by happypoulp** [comment]
Ok, glad to hear that! I am about to try to switch from reflux to flummox and was afraid that isomorphism wasn't completely successful on flummox (it is quite a challenge on Reflux currently).

Thanks for the the clarification! I'll close the issue since it can be safely ignored.
