### ISSUE TITLE
Update a store when another store changes ?

### ISSUE THREAD

**Issue by jide** [acdlite/flummox#153]
I have a store which holds a list of things.

These things can be added as favorites. These favorites are stored in local storage.

When a thing is in favorites, a tick should be displayed in the list of things to show they are in favorites.

What I thought I should do is to listen to changes in the favorites store and then update the things store to add a "ticked" property.

But doing ````flux.getStore('favorites').addListener('change', this.handleFavoritesChanged);```` inside the constructor of the list store does not feel right, right ? (and leads to cases where the list store is not ready yet when the favorites store first fires the change event).

Should I listen to ````addToFavorites```` and ````removeFromFavorites```` actions and use a waitFor ? Then what about the initial state ?

Thanks !

**Comment by acdlite** [comment]
Seems like `ticked` can be a computed property, and you don't need to have a separate store. For instance, you could add a method to your FavoriteStore called `isTicked(thingId)` and use that inside your view. This way you don't have to worry about synchronizing state across separate domains.

**Comment by jide** [comment]
In fact that's what I did first, but my concern is that I would have to wrap my component in a flux container, and having a container deeply inside my component does not seem a good thing regarding decoupling... Makes sense ?

**Comment by tcoopman** [comment]
Without seeing some code it's hard to tell, but why can't your wrap your list in a flux container and give all items the tick as prop?

**Comment by jide** [comment]
So this is what I said in the first place, in this case my problem is how to access the favorites store to populate the ticks ? by listening to the actions ? by listening to all changes from favorites store ?

I'll try to extract this from my code and post it here, but that's really about general architecture when one store depends on another.

**Comment by acdlite** [comment]
> having a container deeply inside my component does not seem a good thing regarding decoupling

My view is that a little coupling inside your views is preferable to coupling between stores.

**Comment by jide** [comment]
@acdlite Ah interesting, I am still wondering what the best practices are, so that's a precious advice.

**Comment by tcoopman** [comment]
I would probably listen to all changes from favorites store on a Component that contains all the items.

I agree with acdlite, it's probably easier if you keep your stores decoupled.

**Comment by jide** [comment]
So in this implementation we would have a ListContainer directly listening to favorites store and when it updates we would populate the items with the "ticked" prop ? Did not think about that, but that sounds good !

**Comment by tcoopman** [comment]
This can be closed then?

**Comment by jide** [comment]
Yes, thank to you both for your answers.
