### ISSUE TITLE
How to use waitFor method of Dispatcher?

### ISSUE THREAD

**Issue by soda29** [acdlite/flummox#155]
Hi acdlite!
Can you please provide an example of how to use waitFor method inside a store or how to access an store inside another store?
The link provided in issue #110  isn't working anymore.

**Comment by acdlite** [comment]
Here ya go: https://github.com/acdlite/flummox/blob/master/docs/docs/api/store.md#waitfor

**Comment by soda29** [comment]
Thank you! I will try it tomorrow.
