### ISSUE TITLE
Losing event click with Async Actions

### ISSUE THREAD

**Issue by soda29** [acdlite/flummox#158]
Hi guys!
I'm trying really hard to detect an issue inside one of my apps that has to do with event clicks not firing when rendering elements that have being stored (in a store) using async methods.
I've uploaded an example here: https://github.com/soda29/flummox_async_store_promises

This is the element i'm rendering using a FluxComponent that listens to the "billing" store.

```javascript
                <FluxComponent connectToStores={['billing']}>
                    <BillForm />
                </FluxComponent>
```

The element has three props that comes from connecting to the store:
__data1__: with data that comes from an API so is using promises and asyc-await functions
__data2__: with data that is assigned through a function not using async-await
__data3__: Data that is assigned in the store class constructor

This is the actual __Actions__ (the url in the API.get and API.get2 calls means nothing).
```javascript
import * as _ from 'lodash';
import { Actions } from 'flummox';
import FluxComponent from 'flummox/component';

class API {
    constructor() {
    }

    get(url, qs) {
        return new Promise( function(resolve,reject){
            resolve([{id: 1, name: 'Data1 Name 1'}, {id: 2, name: 'Data1 Name 2'}, ]);
        } );
    }

    get2(url, qs) {
        return [{id: 1, name: 'Data2 Name 1'}, {id: 2, name: 'Data2 Name 2'}, ];
    }
}

var Api = new API();

export class BillingActions extends Actions {

    loadAllData(filters) {
        try {
            this.setData1(filters);
            this.setData2(filters);
        }
        catch (error) {
            console.error(error);
        }
    }

    async setData1(filters) {
        const data = await this.loadData1(filters);
        return await {data:data};
    }

    async loadData1(filters) {
        try {
            let res = await Api.get('/api/finance/data1', filters);
            return await res;
        }
        catch (error) {
            console.error(error);
        }
    }

    setData2(filters) {
        let data = this.loadData2(filters);
        return {data:data};
    }

    loadData2(filters) {
        let res = Api.get2('/api/finance/data2', filters);
        return res;
    }
}
```

this is the React component class that render the elements:

```javascript
export class BillForm extends React.Component {
    constructor(props) {
        super();
    }
    render() {
        if (this.props.data1.length > 0) {
            var data1 = this.props.data1.map(function(data, keyId){
                return (<div key={'data1-'+keyId} onClick={function(){console.log('clicked!!!')}}>{data.name} - onClick event does not work</div>);
            })
        }
        else {
            var data1 = [(<div key={'none1'} onClick={function(){console.log('clicked!!!')}}>No data 1</div>)];
        }
        if (this.props.data2.length > 0) {
            var data2 = this.props.data2.map(function(data, keyId){
                return (<div key={'data2-'+keyId} onClick={function(){console.log('clicked!!!')}}>{data.name}</div>);
            })
        }
        else {
            var data2 = [(<div key={'none2-'} onClick={function(){console.log('clicked!!!')}}>No data 2</div>)];
        }
        if (this.props.data3.length > 0) {
            var data3 = this.props.data3.map(function(data, keyId){
                return (<div key={'data3-'+keyId} onClick={function(){console.log('clicked!!!')}}>{data.name}</div>);
            })
        }
        else {
            var data3 = [(<div key={'none3-'} onClick={function(){console.log('clicked!!!')}}>No data 3</div>)];
        }
        if (this.props.data4.length > 0) {
            var data4 = this.props.data4.map(function(data, keyId){
                return (<div key={'data4-'+keyId} onClick={function(){console.log('clicked!!!')}}>{data.name}</div>);
            })
        }
        else {
            var data4 = [(<div key={'none4-'} onClick={function(){console.log('clicked!!!')}}>No data 4</div>)];
        }
        return (
            <div>
            {data1}
            {data2}
            {data3}
            {data4}
            </div>
        );
    }
}

BillForm.defaultProps = { data4: Api.getNow() };
```
this is the API Class:

```javascript
class API {
    constructor() {
    }

    get(url, qs) {
        return new Promise( function(resolve,reject){
            resolve([{id: 1, name: 'Data1 Name 1'}, {id: 2, name: 'Data1 Name 2'}, ]);
        } );
    }

    async getNow() {
        return await this.get();
    }
}
```

Problem is all rendered divs fire a click Event except the ones on Data1 that are the ones that are stored using an async-await action.

What am i missing?
I hope i've made myself clear. English is not my primary language and i'm pretty bad at it.

**Comment by soda29** [comment]
Hi guys!
Do you have any idea how to workaround this situation or are you seeing something wrong in this implementation of flummox?

**Comment by bdowning** [comment]
I can't speak to your Flummox issues, as I haven't been using it or Flux long enough to comment, but it doesn't look like you're using async/await right.

Any function marked `async` will implicitly return a Promise when run which will be fulfilled or rejected when that function either returns or throws.  The only place you can `await` is in an `async` function, and the only thing you can `await` on is a Promise.  That will (as the name implies) wait for the promise to fulfill (at which point the caller async function continues with the fulfilled value) or reject (at which point the caller async function throws with the rejection).

In your code above, your sync functions are:

```
    setData2(filters) {
        let data = this.loadData2(filters);
        return {data:data};
    }

    loadData2(filters) {
        let res = Api.get2('/api/finance/data2', filters);
        return res;
    }
```

In the async equivalents:

```
    async loadData1(filters) {
        try {
            let res = await Api.get('/api/finance/data1', filters);
            return await res;
        }
        catch (error) {
            console.error(error);
        }
    }
```

`Api.get(...)` returns a promise.  You `await` on that, which gets the value out of the promise and puts it into `res`.  Then you `return await res`, which is invalid as `res` is not a promise.  This should just be:

```
    async loadData1(filters) {
        try {
            let res = await Api.get('/api/finance/data1', filters);
            return res;
        }
        catch (error) {
            console.error(error);
        }
    }
```

Same thing in:

```
    async setData1(filters) {
        const data = await this.loadData1(filters);
        return await {data:data};
    }
```

`return await {data:data}` is awaiting on a non-promise and is invalid.  This should be:

```
    async setData1(filters) {
        const data = await this.loadData1(filters);
        return {data:data};
    }
```

Finally, in:

```
    loadAllData(filters) {
        try {
            this.setData1(filters);
            this.setData2(filters);
        }
        catch (error) {
            console.error(error);
        }
    }
```

Since you are not awaiting on `this.setData1` it is basically firing it off and not waiting for a result.  Because of this it can never throw.  Remember that as an `async` function `this.setData1` actually returns a Promise.  I suspect what you want is:

```
    async loadAllData(filters) {
        try {
            await this.setData1(filters);
            this.setData2(filters);
        }
        catch (error) {
            console.error(error);
        }
    }
```

Anyway, hope that helps.  It might be beneficial to play with "raw" Promises for a while before trying async/await, because if you don't understand what going on under the hood it can be confusing.

**Comment by soda29** [comment]
Thank you for your time bdowning. I will review this today after work!

**Comment by johanneslumpe** [comment]
@soda29 did you fix your issue?

**Comment by soda29** [comment]
Yes. Thank you very much to @bdowning for the enlightment!

**Comment by johanneslumpe** [comment]
:+1:
