### ISSUE TITLE
mocha chai sinon test envoriment

### ISSUE THREAD

**Issue by tadjik1** [acdlite/flummox#159]
Hello there.

First, thank you very much for perfect tool, it's very useful for me.
I'm newby in flux and reactjs world, so it's very difficult for me to create a test env for my project.

The main problem for me: I don't understand what to do with flux instance, how could I pass it into every test suite for my component?

For example:

my component:
```javascript
import React, { PropTypes } from 'react';
import connectToStores from 'flummox/connect';
import './home.styl';

class HomeHandler extends React.Component {

  static propTypes = {
    flux: PropTypes.object.isRequired,
    series: PropTypes.array.isRequired
  };

  render() {
    let series = this.props.series.map((series) => {
      return (
        <div className="col-md-3">
          <h2>{series.name}</h2>
        </div>
      )
    });

    return (
      <div className="container-fluid">
        <div className="row">
          {series}
        </div>
      </div>

    )
  };

}

HomeHandler = connectToStores(HomeHandler, {
  series: store => ({
    series: store.getAllSeries()
  })
});

export default HomeHandler;
```

and my test:
```javascript
import React from 'react';
import TestUtils from 'react/lib/ReactTestUtils';

import Home from '../index';

describe('home', () => {
  it('renders without problems', () => {

    // I don't know what to do with flux instance - all of flummox component need in it

    //var root = TestUtils.renderIntoDocument(<Home/>);
    //expect(root).to.exist;
  });
});
```

When I'm trying to test my component this way - I catch an error: 
```bash
Error: fluxMixin: Could not find Flux instance. Ensure that your component has either `this.context.flux` or `this.props.flux`.
```

So I understand that is because I didn't create an instance of my flux. But I don't wanna do it for every test. I need to create a helper like this:
```javascript
import React from 'react';
import TestUtils from 'react/lib/ReactTestUtils';

import Home from '../index';

import FluxComponent from 'flummox/component';
import Flux from '../../../flux';

const flux = new Flux();

describe('home', () => {
  it('renders without problems', () => {

    // I don't know what to do with flux instance - all of flummox component need in it

    var root = TestUtils.renderIntoDocument(
      <FluxComponent flux={flux}>
        <Home />
      </FluxComponent>
    );
    expect(root).to.exist;
  });
});
```
 and do it every time or there is another solution?

**Comment by tcoopman** [comment]
@tadjik1 if you need to do something before every test, why not use `before` or ``beforeEach`? See http://mochajs.org/#hooks

**Comment by tadjik1** [comment]
All of my component test need to flux instance. So I don't understand should I initialize my flux inside every tests or could I do it better way.
Btw do you have an production-ready example of application using flummox with some tests? Maybe if I'll see it I could understand this part better.

**Comment by tcoopman** [comment]
I don't have any flummox code with tests yet (normally that will come soon), but if you have some more code, I'm willing to take a look at it.

Also, if you are unit testing your `<Home>` component, why not pass the flux props yourself:
````js
<Home flux={myFluxProps} />
```

That way you can control the props better too for testing.

**Comment by tadjik1** [comment]
@tcoopman ok, thank you. I'm trying to implement it.
