### ISSUE TITLE
Flummox store and React router dynamic segments

### ISSUE THREAD

**Issue by jbmusso** [acdlite/flummox#160]
Greetings,

I'm dealing with the React Router dynamic segments issue when using Flummox (see: https://github.com/rackt/react-router/blob/09fad0b3faf0fe0f39ea2ffbabd221d1207bf20e/docs/guides/overview.md).

When going from `/users/123` to `/users/456` route (clicking on a `<Link to="user" params={{id: 456}} >`, the UserPage component is being rendered with the data from the previous page (ie. `this.context.router.getCurentParams().id` returns 123 even though the router transitioned to `/users/456`). Parts of Flux (Flummox) and React Router are still a bit mysterious to me, so I'm unsure how to deal with this.

What would be the recommended Flummox-way to solve this? React Router suggests implementing a `componentWillReceiveProps()` in the component (see. https://github.com/rackt/react-router/blob/bf89168acb30b6dc9b0244360bcbac5081cf6b38/examples/master-detail/app.js#L94-L96). I foresee this may be a recurrent pattern that may already be addressed at the Flummox-level, but I'm unsure how.

Would you recommend anything to properly handle this case? I started from the Flummox docs example and will happily provide code snippets if needed. Thanks!

**Comment by acdlite** [comment]
Do have some sample code I could look at? Both FluxComponent and the HoC both implement `componentWillReceiveProps()`.

**Comment by johanneslumpe** [comment]
@jbmusso closing this for now. If you still have any questions, please post back here :)
