### ISSUE TITLE
Make connectToStores decorator-friendly

### ISSUE THREAD

**Issue by gaearon** [acdlite/flummox#161]
There's a [stage 1 proposal for ES7 decorators](https://github.com/wycats/javascript-decorators) and there are multiple parties interested in them (Angular, Ember). They are already supported by Babel with `{ "stage": 1 }` in `.babelrc` file.

The way you decorate classes is like this:

```js
@Something({ whatever })
export default class MyComponent { }
```

which desugars roughly to 

```js
class MyComponent { }

MyComponent = Something({ whatever })(MyComponent);
export default MyComponent;
```

It would be nice if `connectToStores` was decorator-friendly.
The only change is to remove the first parameter and make it return a function instead.

Instead of 

```js
class BaseComponent extends React.Component {
  render() {
    return <div/>;
  }
}

const ConnectedComponent = connectToStores(BaseComponent, 'test');
```

vanilla users would write

```js
class BaseComponent extends React.Component {
  render() {
    return <div/>;
  }
}

const ConnectedComponent = connectToStores('test')(BaseComponent);
```

whereas decorator-savvy users could write

```js
@connectToStores('test')
class ConnectedComponent extends React.Component {
  render() {
    return <div/>;
  }
}
```

Some advantages of this way of writing:

* You can `export default` right on the class instead of awkward chain of intermediate classes;
* It's hard to miss `connectToStores` now, and it lives right next to `propTypes`.

Whatcha think about that?

**Comment by acdlite** [comment]
Yeah I like this. I have a branch locally with this enabled; it's been on hold because I want to support action injection, too. https://github.com/acdlite/flummox/issues/132 But in the next version, I think we will rename it from `flummox/connect` to `flummox/hoc` and give it a more flexible interface. So we can make this change now and have users upgrade later.

**Comment by nd0ut** [comment]
Oh, it's nice. In the meantime I use [reactMixin](https://github.com/brigand/react-mixin) and fluxMixin wrapper
```javascript
export var fluxMixin = function(...args) {
  return function(cls) {
    var mix = _fluxMixin(...args);
    return _reactMixin.onClass(cls, mix)
  }
};
```

**Comment by soen** [comment]
Looking forward to see this land in a (hopefully not too distant) future version 👍

**Comment by timbur** [comment]
What's the status on this?  I would like to use this right meow.

**Comment by vjpr** [comment]
Such a tiny change. Hope it happens!

**Comment by istarkov** [comment]
For now for flummox 4.x i've wrote

*fluxComponentDecorator.js*
```javascript
import React, { Component } from 'react';
import FluxComponent from 'flummox/component';
import shouldPureComponentUpdate from 'react-pure-render/function';

export default function fluxComponentDecorator(fluxComponentProps) {
  return DecoratedComponent => class FluxComponentDecorator extends Component {

    static displayName = (DecoratedComponent.displayName || DecoratedComponent.name || 'Component');

    shouldComponentUpdate = shouldPureComponentUpdate;

    constructor(props, context) {
      super(props, context);
    }

    render() {
      return (
        <FluxComponent {...fluxComponentProps}>
          <DecoratedComponent {...this.props} />
        </FluxComponent>
      );
    }
  };
}
```


and use it like
```javascript
@fluxComponentDecorator({
  connectToStores: {
    route: (store /*, props*/) => ({
      routePath: store.getRoutePath(),
      routeParams: store.getRouteParams()
    })
  },
  injectActions: {
    route: (actions) => ({
      onGotoLink: actions.gotoLink
    })
  }
})
export default class Link extends Component {
 ...blablabla
}
```
