### ISSUE TITLE
doc site broken in IE11 win7

### ISSUE THREAD

**Issue by box-turtle** [acdlite/flummox#167]
I am attempting to troubleshoot my own project running with webpack/babel where I was getting an "Invalid Calling Object" error when calling an async operation using IE11. The error occurs in the file es6.promise.js at the line:

```
if(isReject || chain.length)asap(function(){
```
So this may be some kind of error related to the babel pipeline. No errors in firefox/chrome on windows or mac, only IE.

Just to confirm that flummox async methods work in IE I navigated to the Flummox doc site at http://acdlite.github.io/flummox/ and all links are broken in IE11 - clicking on any link give a github 404. Everything works fine in chrome/firefox. 

Just curious if anybody else is seeing issues w/IE 11.

**Comment by box-turtle** [comment]
The issue is with how IE handles aliasing of functions off the window object. See issues 

https://github.com/caolan/async/issues/299

https://github.com/substack/node-browserify/issues/237

Stupid quick fix is to add this to a script tag in your html file before including your main script:

```
    window.setImmediate = window.setImmediate.bind(window);

```

I guess this is something that should be filed against babel?

**Comment by danieljuhl** [comment]
@box-turtle we are seeing the exact same issue on a project using flummox, babel and webpack.
