### ISSUE TITLE
connectToStores breaks "routerWillRun"

### ISSUE THREAD

**Issue by merk** [acdlite/flummox#168]
I've been trying to combine the HoC/connectToStores wrapper with the example from the docs code where you run a static function on a component before the router runs.

The functions havent been running and I've tracked it down to the wrapper.

Is there a way to handle this situation or should a component using a HoC wrapper not have a routerWillRun method?

**Comment by acdlite** [comment]
If you use an HoC, you need the static method to be on the top-most component. You can do this manually like so:

```js
class MyComponent extends Component {...}
MyComponent = connectToStores(MyComponent, {...});
MyComponent.routerWillRun = function() {...}
export default MyComponent;
```
