### ISSUE TITLE
Issue with server rendering and HoC

### ISSUE THREAD

**Issue by dozoisch** [acdlite/flummox#170]
Alright, I don't know if the issue is on the way I'm doing things, but I have a weird issue when using HoC on server side rendering.

My stores fetch their data automatically when asked for

ex:

```js
const ConnectedApplyToEvent = connectToStore(ApplyToEvent, {
  event: store => ({
    events: store.getUpcomingEvents(),
  })
});
```

`store.getUpcomingEvents()` will return the events if they are already fetched, or will create the action to fetch them.

So when rendering server-side, I just do  `renderToString` first. This create the actions needed, and once all the actions are finished, I do a second `renderToString` and the view then gets rendered with all data needed.

When the store dispatches the change event from loading, this function gets called:

https://github.com/acdlite/flummox/blob/master/src/addons/reactComponentMethods.js#L185-L190

```js
function createStoreListener(component, store, storeStateGetter) {
  return (function () {
    var state = storeStateGetter(store, this.props);
    this.setState(state);
  }).bind(component);
}
```

The problem is that the setState is called on a non-mounted component which creates an error afterwards. That error then stops the dispatching and "everything breaks".

The only fix I could see was to check whether the component was mounted before calling the set state. And I'm using a custom `this.mounted` instead of `this.isMounted()` because `isMounted` is deprecated...

So
```js
// reactComponentsMethod.js
componentDidMount() {
   this.mounted = true;
}

function createStoreListener(component, store, storeStateGetter) {
  return (function () {
    var state = storeStateGetter(store, this.props);
    if (this.mounted) {
      this.setState(state);
    }
  }).bind(component);
}
```

I don't know if there is another way of doing it?

**Comment by dozoisch** [comment]
This is the branch I'm using on my own right now.

https://github.com/dozoisch/flummox/commit/77e7d48a1fb4b9831bd8aca0e7da7b2a0319cd69

**Comment by dozoisch** [comment]
If anyone is interested, I have a working example here : https://github.com/dozoisch/pointsgenie/pull/30

with server-side rendering. The only problem is that I had to use 2 forks for that.

**Comment by burabure** [comment]
im not sure if the following is the direct  cause of your issue, but: 
Stores shouldn't fetch, do async or side-effecty things.

try putting your async/fetching in actions and passing those results to stores.

**Comment by dozoisch** [comment]
@burabure Alright, might be an issue with the way I'm doing it then.

I'm not sure about that philosophy'though. I've seen both implemented  ways a lot in Flux-ies.

Anyway, if the stores don't fire actions, it means whether you need actions to know about store state (you don't want to be fetching data constantly for no reason) OR then every component needing the data needs to check if the data is already fetched, and then fire the actions if it's not.

If your stores don't do fire actions, you need to have another layer of functions (like the routerWillRun that checks if the data is fetched, and fires actions if it's not.) And you get to have a lot of code repitition that way. And it also means that you need the top handler to know about all of his child, instead of having components that needs data be connected to the store (with the HoC) and ask for his own data.

**Comment by burabure** [comment]
take a look at this presentation, also here's an awesome checklist by Dan:

![cdyaq-bw0aesyp1](https://cloud.githubusercontent.com/assets/3132298/7417527/0b41918c-ef3d-11e4-957f-bcc491b466ac.png)

**Comment by dozoisch** [comment]
@burabure Alright, I can refactor the stores to be totally syncrhonous.

But where would you put the fireing of actions to fetch the data. 

- You will need to have a routerWillRun function that needs to know about all of his childs, (or actually all the child that are not handlers). And this fires actions. You can then wait until theses actions have loaded the data into stores to do the server render.
- You check if the data is available on willTransitionTo or fire the actions from there. Meaning you have duplication checks for every component who needs similar data (but are not necessarily on the same page).
- You do the fetch on componentDidMount (like most examples) which means you are not server rendering, but client rendering.


I'm kind of lost on how to do it. I've been trying to figure it out in the past days, but fireing actions from the store was the simplest way I found to make it work both server-side and client side.

Any comp just ask for data, and it will eventually receive it. All you needed to change on the server was the actions (because they need to use a different api so that they fetch data from database directly and not from ajax requests), and you have to render twice. First time, the components auto-register the data they need, once it's loaded you render and send to client.

**Comment by bhj** [comment]
I ran into this with Reflux but [according to the author](https://github.com/spoike/refluxjs/issues/158#issuecomment-67444098) it's OK for a store to fire an action, at least sometimes :p

**Comment by burabure** [comment]
@dozoisch I don't know what would be best for your app, but there's plenty of places you can fire the action on components; getInitialState or constructor, componentWillMount...

flux is very new, and the community is starting to figure where the footguns are; firing actions from stores is one because it can cause cascading updates very easily.

**Comment by dozoisch** [comment]
@burabure I guess that makes sense, I can change where actions fireing happens. There is still one issue though (that is the same).

The connectToStore register callbacks before the component is mounted. (It registers the stores callback on initialization.) And if I'm not mistaken, renderToString will initialize the components, but will never mount them. So if an actions completes, juste after a renderToString, the callback will fire setState on a non-mounted component. Which shouldn't be possible?

I can do some more testing, but I think that's what is happening.

**Comment by burabure** [comment]
from the react docs 

```Render a ReactElement to its initial HTML. This should only be used on the server. React will return an HTML string. You can use this method to generate HTML on the server and send the markup down on the initial request for faster page loads and to allow search engines to crawl your pages for SEO purposes.

If you call React.render() on a node that already has this server-rendered markup, React will preserve it and only attach event handlers, allowing you to have a very performant first-load experience.```

so it seems to me that it shouldn't be an issue.

**Comment by dozoisch** [comment]
The error happens server side not client-side. It happens after the render to string, once the actions fnishes and updates the stores. The store tries to setState on a component that is not-mounted (but has been rendered with `renderToString()`). I'll try to investigate more to see why the callback is registered when the component is not "mounted" directly.

**Comment by burabure** [comment]
is difficult to be certain of where the issue is occurring without looking at the project itself. could you post the offending component code?

**Comment by burabure** [comment]
ok, I found the cause. ```renderToString``` is meant to be synchronous for now. here's the recomendation from pete hunt on this:

https://github.com/facebook/react/pull/982
>I think that data fetching is workable even in a sync world. You can just move the asynchronicity outside of React. You can even put the code for data fetching alongside your React component, just don't call render() until all the data is fetched and pass the data in as a top-level prop.

so I would move the data fetching to a helper-like js file on /utils and call that on actions and before rendering the component on the server.

**Comment by dozoisch** [comment]
Alright, I'll take  a look at this. My goal was to be able to call renderToString first (which would fire the actions), I wait until actions have completed then call another renderToString with all the data now in the stores. Maybe I can disable the change event from the store when on server or something! I'll get back to you, thanks for helping.

**Comment by burabure** [comment]
I am glad I was able to help. Let me know how you solve it at the end =)

**Comment by dozoisch** [comment]
@burabure I've did some more investigations and connectToStore adds the
listeners before the componentDidMount. When static rendering
(`renderToString` for ex), the only lifecycle function called is componentWillMount. 
DidMount and WillUnmount are never called. In connecToStore, the 
listeners are added at inialization.

That means that if I fire actions at initialization, or at willMount it will do the exact same issue. That I have right now.

Solution I can see is to change the moment listeners are added.

At initialization, create a listeners map which is only "added" at
component did mount. This requires very few changes. You just push them in an
array and at didMount you go through and add the "change" event.

ex:

```js
// instead of store.on("change", listener); you do:

this.listenersToAdd.push(() = > {
  store.on("change", listener);
});

then:
componentDidMount() {
  for (listenerToAdd of this.listenersToAdd) {
    listenerToAdd();
  }
  delete this.listenersToAdd; // or just this.listenersToAdd = [];
}
```

This way, stores won't get a setState event when not mounted. Because right now,
if for any reason, someone does a renderToString, then fires an action (from
any function) it'll just do a bad setState. (Because components are not mounted)

**Comment by dozoisch** [comment]
@burabure Any thoughts on that?
