### ISSUE TITLE
Accessing store state in static class methods

### ISSUE THREAD

**Issue by aparticka** [acdlite/flummox#175]
I'm trying to implement authentication in my app using React Router and the static `willTransitionTo` method to determine if the page should be shown or not, depending on if the user is logged in or not. I have an `AuthStore` class that I've connected to my component, but am unable to access the props while in the `willTransitionTo` method as it is static.

I was wondering if there was a better way to do this, or how others may have worked around it.

**Comment by Simonify** [comment]
If you're passing your Flux instance using context, you should be able to use the `transition` argument to the `willTransitionTo` method to access your store.

```
static willTransitionTo(transition) {
    if (!transition.context.flux.getStore('auth').isAuthenticated()) {
      transition.redirect('/sign_in');
    }
}
```

**Comment by dozoisch** [comment]
related: https://github.com/rackt/react-router/pull/590

**Comment by aparticka** [comment]
Thanks @dozoisch, seems I'll have to either wait for the pull request to be merged into react-router or use the fork. Closing this as it doesn't deal with flummox directly.
