### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by johanneslumpe** [acdlite/flummox#180]
As we talked about this a bit before, I wanted to open up this issue to keep track of the progress.

From my experience what needs to be done is:

* remove source maps from the distribution (the packager doesn't like those)
* replace all imports for `react` with `react-native`

The files in question are:

`src/addons/connectToStores.js`
`src/addons/FluxComponent.js`
`src/addons/reactComponentMethods.js`

I propose that those will be name-spaced, so we can import them like this:

`import {FluxComponent} from `flummox/addons/react`
`import {FluxComponent} from `flummox/addons/react-native`

The two files `react` and `react-native` would each `import` their required version of react and inject it into the addons.

All parts of the addons which are non-static or use parts of `react` like `PropTypes` or `Component` must be wrapped in a function in order to be initialized properly when imported.

Thoughts?

**Comment by acdlite** [comment]
Thanks! I opened a pull request. Let's track this there: https://github.com/acdlite/flummox/pull/181
