### ISSUE TITLE
Flux.createActions extra arguments

### ISSUE THREAD

**Issue by chrismbeckett** [acdlite/flummox#183]
It would be really useful to inject stuff into actions the way you can with stores by allowing extra arguments to be provided to the createActions method. This would allow the Flux component to control context for flux components the way that React components have context as well.

**Comment by acdlite** [comment]
Is this what you mean?

```js
flux.createActions('myActions', MyActionsClass, ...constructorArgs)
```

You can do that already :)

**Comment by chrismbeckett** [comment]
Ah, I didn't check the code. I was looking at the docs for Flux component and it specifically says you can provide extra arguments to createStore but doesn't say you can do it for createActions. Have a convo on Gitter right now and checked the source and yes, thank you, you can already do it. Nice!
