### ISSUE TITLE
Add support for bower 

### ISSUE THREAD

**Issue by lasekio** [acdlite/flummox#184]
What about bower support?

**Comment by david0178418** [comment]
This would be a great addition.

**Comment by bradobro** [comment]
Agreed. Seems like node_modules-sources builders are gaining popularity, but they seem to make much larger bundles than my bower builders.

**Comment by yanmagale** [comment]
Bower is deprecated. I believe that not necessary  to create this. They recommend Webpack, Yarn or NPM.
