### ISSUE TITLE
problems with server side rendrering

### ISSUE THREAD

**Issue by tadjik1** [acdlite/flummox#186]
Hello there.

I have a problems when trying to render my app in nodejs envoriment. The same error I saw in #61 but I don't understand how to fix it.
My code is very simple — https://github.com/tadjik1/soundcloud-player/blob/feature/integrate-with-flummox/scripts/server/appView.js
When I run my server ```node build/server.js``` and open localhost:3000 I saw an error
``` Error: fluxMixin: Could not find Flux instance. Ensure that your component has either `this.context.flux` or `this.props.flux`.```

Code look like (it's koajs server):
```javascript
app.use(function* appHandler() {
  const flux = new AppFlux();

  try {
    Router.run(routes, this.url, (Root, state) => {
      const html = React.renderToString(
        <FluxComponent flux={flux}>
          <Root {...state} />
        </FluxComponent>
      );

      console.log(html);

      this.body = 'lala';
    });
  } catch (error) {
    throw error;
  }
});
```
------------------------------------------------------
upd: in the same time on client side this code works well

Please help me resolve this problem.

**Comment by tadjik1** [comment]
Ok, I checked some different variants and noticed that problem with webpack. But I still can not resolve it. I'll close this issue, but if someone have an answer - it would be cool.

**Comment by tadjik1** [comment]
It's very strange:

in nodejs env I have this errors:
```
Warning: Failed propType: Invalid prop `flux` supplied to `FluxComponent`, expected instance of `Flux`.
Warning: Failed Context Types: Invalid child context `flux` supplied to `FluxComponent`, expected instance of `Flux`.
```

but in client side - there are no this errors. I use one webpack config and one env variable. Maybe someone know what's wrong with this config?
app example: https://github.com/tadjik1/soundcloud-player
just clone, npm i and then gulp.

**Comment by dariocravero** [comment]
@tadjik1, [this](https://github.com/acdlite/flummox-isomorphic-demo/blob/master/src/server/routes/views/appIndex.js#L39-L42) seems to do it:

```js
    html = React.withContext(
      { flux },
      () => React.renderToString(<Handler {...state} />)
    );
```

**Comment by tadjik1** [comment]
But
https://github.com/facebook/react/blob/a411f3e0dcac3cada4ce0acf6603bbb8ff7024a6/src/core/ReactContext.js#L54

**Comment by dariocravero** [comment]
Oh :/, forgot about that, well spotted.

So, coming back to your original logic, I put together a simplified example that just renders a component and [it works fine](https://github.com/dariocravero/flummox-koa/blob/master/index.es6#L24-L26).

I'll try with more complex scenarios like importing FluxApp instead of defining it on the same file, converting the code with babel and running it with regular node, etc. but I don't see any reason why it shouldn't work then other than your "packer" doing something funky on the way...

**Comment by tadjik1** [comment]
yep @dariocravero I've made the same conclusion, but unfortunately it's too difficult for me - to understand what's happening inside in webpack =)

anyway thank you very much!

**Comment by bgryszko** [comment]
Same thing here with webpack – no solution yet.

**Comment by tadjik1** [comment]
@dariocravero @bgryszko The problem was with webpack config, key "externals". I just use this configuration: 
https://github.com/tadjik1/soundcloud-player/blob/master/webpack.config.js#L87
and it works well for me (I don't create a single large file in nodejs env)

**Comment by dariocravero** [comment]
Well, the way I see it, your server side code shouldn't need to run through webpack anyway. You can use babel to transpile whatever your runtime can't run and that should be it really...

**Comment by tadjik1** [comment]
yep, you are right. but right now I am doing some others stuff, and I'll create a better solution before launching project. Right now it works, and for me it's enough)

**Comment by dariocravero** [comment]
:)

**Comment by rossthedevigner** [comment]
@bgryszko Did you ever get it to work?

**Comment by bgryszko** [comment]
I've switched to Redux
