### ISSUE TITLE
Not possible to extend subclass of Store?

### ISSUE THREAD

**Issue by olavk** [acdlite/flummox#190]
I tried to make this work. My store classes are extended this way:
```
Store
  -> ImmutableStore (implements custom assignState)
    -> ContentStore
      -> UserStore
      -> EventStore
      -> ManyOtherContentStores
```
Every subclass of ContentStore has "update" action (as you would). If you fired one of those actions, then my ImmutableStore#assignState would be called for **each one of those stores**.
One update. Many state assignments.
I moved "assignState" implementation into each one of those stores. Problem solved.

Am I doing it wrong, or is there a problem with Store.js:71 _assignState()?

**Comment by johanneslumpe** [comment]
That should not call it for each store, when one store calls the method. Can you post some code so we can figure this out?

**Comment by johanneslumpe** [comment]
I will close this for now. If you still have problems, please comment and we can re-open this @olavk
