### ISSUE TITLE
How to deal with Stores that depend on other Stores

### ISSUE THREAD

**Issue by joaovpmamede** [acdlite/flummox#193]
By reading the documentation, I see we are discouraged of using waitFor, because it introduces dependencies between stores.

What about when there's a store that needs to update when a different store emits a change (e.g. after saving an item with a new id)?

Right now what I’m doing it’s pretty ugly.
I’m saving a property on the construtor by getting the store that I need to get the id from, via the flux arg on the constructor.

```javascript
class Foo extends Store {

  constructor(flux) {
    super();

    const fooActions = flux.getActions('foo');

    this.barStore = flux.getStore('bar');

    this.register(fooActions.addItem, this.onAddItem);

    this.state = {};
  }

  ...

}
```

After, on my handler I use the waitFor method and use that saved store property to call a method to retrieve the id that I need.

```javascript
onAddItem() {
    const barStore = this.barStore;

    this.waitFor(barStore);

    const itemId = barStore.getItemId();
 
    // save itemId on this store
    ...
}
```

I tried to find some examples where people have used waitFor or had some kind of relation between data in separate stores, but was unable to find any.
What would be the ideal approach when you need some data from other stores?

**Comment by laskos** [comment]
U can pass to store's constructor another one:

```javascript
// In flux constructor
this.createStore("foo", Foo);
this.createStore("bar", Bar, this.getStore("foo"));
```

**Comment by joaovpmamede** [comment]
@laskos I almost did that but ended up passing flux to constructor.
I guess sometimes there's no way of avoiding some coupling, or maybe I just need to model my data in a better way.
