### ISSUE TITLE
Better explanation of isomorphic async state loading

### ISSUE THREAD

**Issue by LeviBotelho** [acdlite/flummox#198]
First of all Flummox is great. I really like the work you've done.

I'm working on an app where I have a search page that takes a URL parameter, submits it to an API, and displays the results. The documentation isn't very clear as to how to accomplish this in an isomorphic manner. From the example code it appears that on the server side the stores have to be pre-loaded with data before rendering the page. I'm not sure if this is in fact correct, or if there is a better way, but it would be extremely helpful to make mention of this on the site, as Flummox's isomorphic support is a big selling point for the library.

**Comment by jbmusso** [comment]
Indeed, you have to asynchronously fetch data first, then render your application.

You can browse the `/docs` folder of this repository for an example using React Router and Koa. Data is fetched at [docs/src/server/appView.js#L49](https://github.com/acdlite/flummox/blob/9dc844fb80df65cbe9ea659feb02e56cce81d388/docs/src/server/appView.js#L49). Application is rendered after as a string (see [lines 53-57](https://github.com/acdlite/flummox/blob/9dc844fb80df65cbe9ea659feb02e56cce81d388/docs/src/server/appView.js#L53-57)) then sent over the wire ([line 66](https://github.com/acdlite/flummox/blob/9dc844fb80df65cbe9ea659feb02e56cce81d388/docs/src/server/appView.js#L66)).

Especially, see the [docs/src/shared/performRouteHandlerStaticMethod.js](https://github.com/acdlite/flummox/blob/9dc844fb80df65cbe9ea659feb02e56cce81d388/docs/src/shared/utils/performRouteHandlerStaticMethod.js) file imported in `docs/src/server/appView.js` which contains a function that, for all routes, finds all RouteHandlers with a `routerWillRun` function and execute that function. A `routerWillRun` function will typically execute one or more Flux actions which remotely fetch the data (typically via HTTP). Have a look at [DocActions.js](https://github.com/acdlite/flummox/blob/9dc844fb80df65cbe9ea659feb02e56cce81d388/docs/src/shared/actions/DocActions.js) for such actions: these actions fire asynchronous HTTP calls which then update the stores' states, allowing your Flummox application to be rendered server-side with populated stores.

If you wish to also send your store states along the initial HTTP call to your clients, you can do this right before sending the data:

```javascript
  const fluxState = flux.serialize();

  this.body = nunjucks.render('index.html', {
    appString,
    fluxState,
    env: process.env,
```
Make sure:
* your stores implement `serialize()` and `deserialize()` methods (`JSON.stringify()` and `JSON.parse()` could do it, but **be aware of security issues in doing so**, especially XSS attacks, see https://github.com/acdlite/flummox/pull/104 : sanitize your data first) - you get the freedom here.
* your `index.html` template prints out the `fluxState` constant in some way (for example, in a `<input type="hidden" value={{fluxState}} id="init-data">` field of some kind, but other ways are valid)
* you call `flux.serialize()` with the content of that `<input>` (or whichever solution you picked in previous step) in your `client.js` file right before rendering your Flummox application:

```javascript
const flux = new Flux();
const fluxState = document.getElementById('init-data').value;
flux.deserialize(fluxState);

// then
// Router.run(routes ...
```

**Comment by LeviBotelho** [comment]
> If you wish to also send your store states along the initial HTTP call to your clients, you can do this right before sending the data...

Brilliant. This and the explanation of the static method calls are just what I needed. Thanks so much.

**Comment by dlindenkreuz** [comment]
What would be the most elegant way to load information directly from a database driver (e.g. Postgres, MongoDB, RethinkDB — no HTTP) into the stores?

This would obviously not work client-side, so how would I integrate that specific bit of data fetching into the isomorphic system?
