### ISSUE TITLE
How to use an action for registerAsync failure? flummox and errors stop the flow.

### ISSUE THREAD

**Issue by poeticninja** [acdlite/flummox#199]
I have two stores (queries and notifications) and actions for both stores. One of the query actions returns an [Axios](https://github.com/mzabriskie/axios) promise. When there is an error I would like to send the error message to the notification action and from there have the notifications store pick it up and add it to the stores state.

Here is the query store and actions.
```
import {Store} from 'flummox';

export default class QueryStore extends Store {
    constructor(flux) {
        super();

        this.notificaitonActions = flux.getActions('notifications');
        const queryActions = flux.getActions('queries');

        this.registerAsync(queryActions.newQuery, null, this.handleNewQuery, this.handleNewHttpError);

        this.state = {
            data: []
        };
    }
    handleNewHttpError(response){
        this.notificaitonActions.newHttpError(response);
    }
    this.handleNewQuery(){
        // do stuff with state here.
    }
}
```

```
import {Actions} from 'flummox';
import Axios from 'axios';

export default class QueryActions extends Actions {
    newQuery(url){
        return Axios.get(url);
    }
}
```

For some reason the notification action gets trigger but the notifications store handler never gets triggered. It seems to eat up the error.

Here is the notification actions and store.

```
import {Actions} from 'flummox';

export default class NotificationActions extends Actions {
    newNotification(notification){
        return notification;
    }
    newHttpError(response){
        console.log('we made it into the action'); // gets called
        return response;
    }
}
```

```
import {Store} from 'flummox';

export default class NotificationStore extends Store {
    constructor(flux) {
        super();

        const notificationActions = flux.getActions('notifications');

        this.register(notificationActions.newHttpError, this.handleNewHttpError);

        this.state = {
            notifications: []
        };

    }
    handleNewHttpError(response){

        console.log('nothing in here ever gets called');
    }
}
```

Is there something I am missing or just not understanding about registerAsync or flummox and errors?

Thanks!

**Comment by poeticninja** [comment]
I am realizing the error is actually,
`Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.`

This error was not showing because the error was swallowed. Now I need to get around this new apparent issue. Any suggestions welcomed.

But I am also concerned about the errors not showing. I have found many times errors not showing and I have to do some crazy work around to find out what error is happening between an action and a store. Is anyone else having issue with this and finding ways for better debugging problems?

**Comment by johanneslumpe** [comment]
You must not trigger actions from within stores. You could either add a `catch` handler to the promise and trigger the notification action from there, or you could have the notification store listen to the async query action as well, but only provide a failure handler. A third options would be to use [registerAllAsync](https://github.com/acdlite/flummox/blob/master/src/Store.js#L109) to listen to all async actions in your notification store and process them all with generic success/failure handlers.

As for the errors: If you happen to use `bluebird` as promise library, then you can add a handler for unhandled rejections and just re-throw the error there. It will then show up.

**Comment by poeticninja** [comment]
Great to know about actions shouldn't be in stores! :smile: 

It looks like registerAllAsync is perfect for the problem I am trying to solve! I can't wait for the documentation on that to be merged. I didn't even know about it!

Thanks a lot!

In regards to using `bluebird` I will have to look into that. At the moment I am just using the promises that babel provides.
