### ISSUE TITLE
Dispatch error with multiple store actions.

### ISSUE THREAD

**Issue by poeticninja** [acdlite/flummox#203]
I have a notification store that is registered to all other store failures using `registerAllAsync`. This is great because I can catch all errors and place them there. Once an error is here I would like to have a component to show the error (or redirect the user depending on the error) and then send an action that removes the notification.

I am having a problem because no action will run right after. I am unable to execute a notification remove action. If I wrap the new action I want to run in a try/catch I get this error.
`Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.`

How does a person get around this?

**Comment by bdowning** [comment]
If you're sure you want to do it you can easily defeat the Dispatch loop checking by running your action in a 0-ms setTimeout.  I've had to do that when I wanted to cause a redirect (via action) as a result of data coming in from the server (hence from another action).  It's probably a sign that I'm doing Flux Wrong(tm), but I couldn't figure out another way to do it that wasn't an even more horrible kludge.

I figure the setTimeout is a pretty good visual indication that "Magic's happening here, watch out!" anyway.

**Comment by johanneslumpe** [comment]
You could compose your actions differently. For example you could do something like this:

Inside your component:
```javascript
const flux = this.props.flux;
const actionToExecute = flux.getActions('api').someAction;
const metaActions = flux.getActions('meta');
metaActions.executeAsyncAndNotify(actionToExecute, [args, to, apply])
```
And the `executeAsyncAndNotify` action could be like this:
```javascript
async executeAsyncAndNotify(action, arguments) {
   // not sure whether the action methods are autobound,
   // this might have to look different
  try {
    await action.apply(null, arguments);
  } catch (err) {
    // at this point your error should have been propagated to the notification store
   // execute your removal action here.
  }
}
```

It's just an idea because I'm not quite sure whether it will solve your problem, because technically you need your timeout anyway. You don't want you notification to be hidden instantly, do you? Else there wouldn't be much sense in showing it at all. But if you didn't use `setTimeout` explicitly, and were to use bluebird, you could use `Promise.delay(x)` instead of a normal timeout. Then you could write something like this in your error block:

```javascript
try {
 /* ... */
} catch (err) {
  await Promise.delay(500);
  // call notification removal action here
}
```

**Comment by poeticninja** [comment]
Thanks guys, the setup timeout is what I needed. Another option that worked but I was not going to do was connect directly to the store in my component. Like @bdowning said, worse kluge than a setTimeout. :smile: 

@johanneslumpe Thanks for taking the time to explain a different way to handle actions. I havent gone down the road of adding async and await yet to the project. I almost did to see if that might help this problem. (I will have to considering it again!)

:+1:
