### ISSUE TITLE
Serialization and deserialization of stores

### ISSUE THREAD

**Issue by gilesbradshaw** [acdlite/flummox#204]
Where the server fetches data asynchronously into stores as part of rending the page serializes the data and sends it to the browser together with the rendered markup, the browser then renders the markup as is and deserializes the data into stores so it can pick up from where the serer left off.  With apologies for my obtuseness - I can see that this can be done with flummox but not how,

**Comment by johanneslumpe** [comment]
First of all your `Flummox` instance has a `serialize` and a `deserialize` method. On the server you fetch your data, then you create a JSON string of your data like this: 
```
var dataString = JSON.stringify(yourFlummoxInstance.serialize())
```
This string you can then embedd into your template, maybe like this (use whatever templating engine you'd like, or render it within a react component):
```
  window.__data = dataString;
```
Then on the client-side you again instantiate your `flummox` instance and hydrate it with the data:
```
yourFlummoxInstance.deserialize(window.__data);
```
Now all the data which you had on the server resides on your client-side stores.

It is important to note that you have to specify a `serialize` and a  `deserialize` method on each store, which you want to hydrate/de-hydrate. The former gets passed in the current state object and expects you to return a string. The latter gets passed in a string and expects you to return a new state object.

**Comment by gilesbradshaw** [comment]
Thank you

**Comment by johanneslumpe** [comment]
Sure :) If this is finished, please close the issue.
