### ISSUE TITLE
How do components call actions on initial render?

### ISSUE THREAD

**Issue by gilesbradshaw** [acdlite/flummox#205]
If my components call actions when first rendered + when props change which result in data getting sent back through stores - how is this achieved isomorphically with flummox?  Ie so that these actions are called and the stores waited for on the serer before the rendered markup is sent back?|

**Comment by johanneslumpe** [comment]
For this you most likely want to fetch your data outside of your components, not within lifecycle hooks.

**Comment by gilesbradshaw** [comment]
"On the server-side you have to pre-fetch your data, as the rendering process is sync"

It need not be though...

Take a look at

https://github.com/ericclemmons/react-resolver/pull/34

This lets you do (on the server)

````
router.run((_Handler)=>
                  <_Handler/> 
      .then(innerHTML=>{
        res.send(
          React.renderToStaticMarkup(
            <HtmlDocument
              resolverScript={innerHTML.data}
              script={webpackStats.script}
              css={webpackStats.css} innerHTML={innerHTML.toString()}>
            </HtmlDocument>
          )
        );
      }
    ));
});

````

HtmlDocument is a component to render an html document - but the point is it is asynchronously obtaining the rendered html and state to send to the client.  So the data requirements can be located with the components rather than the routes.  That's where it belongs imo - as in Relay.

however that isn't flux..  what In am getting at is how this could be implemented with a flux architecture.

**Comment by johanneslumpe** [comment]
The point here is that `resolver` still prefetches your data. AFAIK it renders the tree of components normally, but all `Container` components will not render until they have their data. It still pre-fetches the data. But it allows you to co-locate your data requirements. which is pretty much the same I have been saying (just that I said you should do it in a static method). The difference is that the way they fetch data is decoupled from react-router and coupled to the resolver. 

And the rendering process of react is still sync as you can see in your example - there is the usage of `then` indicating that an async process has to finish before the final render can occur.

Also, are you sure that you can do `<Handler />.then(...)` ? Maybe I'm wrong but I doubt that that example works like that.

**Comment by gilesbradshaw** [comment]
apologies - I posted that wrong I removed a bit of extra jsx and a bit extra by mistake (long day)  it should be 
````
router.run((_Handler)=>
      Resolver.renderToString(
              <_Handler/>
       )
      .then(innerHTML=>{
        res.send(
          React.renderToStaticMarkup(
            <HtmlDocument
              resolverScript={innerHTML.data}
              script={webpackStats.script}
              css={webpackStats.css} innerHTML={innerHTML.toString()}>
            </HtmlDocument>
          )
        );
````
So Resolver is asynchronously rendering the Handler which is produced by router and returning a promise for a rendered string.
I shall have a play with it more and post again.  I am pretty sure that the way it works is that if say the component asynchronously fetches a list then renders a child component for each item in the list which in turn does an asynchronous fetch &c &c then the whole tree of asynchronous fetches can be performed on the server before the promise returned by Resolver is resolved.  I'll make sure it can do that...

This is how I am creating a resolvable component (setTimeout is mimicking an asynchronous fetch).  an immutable List then gets passed in to the component via props.   This is how |I am wondering if FluxComponent's connectToStores (or similar) could be made to behave.

````
export var YoAlt = Resolver.createContainer(InnerComponent, {
  resolve: {
    list: ()=>
     new Promise(
        resolve=>
          setTimeout(
            (()=>{
                console.log("promise resolving...");
                resolve(new List([{id: 0, content: "ahhhh"}]));
              }
              ),
            1000)
        )
  }
});
````

**Comment by johanneslumpe** [comment]
Yes, this is the same thing I said: you still need to fetch asynchronously before doing the final render. i suggested doing it outside of the render process, resolver checks the wrapped components during rendering. But for that it needs a custom render function. With the resolver you also cannot just call any type of action. You need to provide a `resolve` action for the container in order for this to work.

**Comment by johanneslumpe** [comment]
@gilesbradshaw Did this help you, or are there still questions? :)

**Comment by gilesbradshaw** [comment]
very good thanks - I shall close it

**Comment by johanneslumpe** [comment]
:+1:
