### ISSUE TITLE
Where to clean-up stores

### ISSUE THREAD

**Issue by vesparny** [acdlite/flummox#21]
Imagine the following scenario:
* I have a search form, when I submit it I pass the query string to another route which will use it to trigger an action to fetch data, populate a list in a store and display it in the page.
* I came back to the previous page, change the query and submit again.
* When I land to the list page, I see the previous search result because I haven't cleaned the store, and as soon the server call returns, I'll see new the new list.

I was wondering if you have a good pattern to suggest me in order to cleanup the stores.
Would be a good solution return a copy of the state in the store, and just earlier clean it up?
This would be a method in a Store
```js
getDataFromStores() {
    //FIXME I don't know if this is the best approach to reset store status
    var ret = this.state.data;
    this.state.data = Immutable.List(); // restore the store
    return ret;
  }
```
It sound weird to me.
Either way, another action to clean everything up and restore the store at its initial state?

**Comment by acdlite** [comment]
If I understand correctly, you want to clear the stores whenever a new query is submitted?

Sounds like it could be a good use case for the async action handling API we discussed in #14 

```js
class MyStore extends Store {
  constructor(flux) {
    super();
    let actions = flux.getActions('myActions');
    this.registerAsync(actions.search, this.handleSearchBegin, this.handleSearchSuccess, this.handleSearchFailure); 
  } 

  handleSearchBegin() {
    // Clear results
    this.setState({
      results: Immutable.List()
    });
  }

  handleSearchSuccess(results) {
    this.setState({ results }); 
  }

  handleSearchFailure(error) {
    // handle error somehow
  }
}
```

(Note that this feature isn't implemented yet... I'm start working on it sometime today)

Also, you should never set store state using assignment (`this.state.data = ...`). Always use `setState()`, as in React. This ensures that the change event is fired properly.

**Comment by vesparny** [comment]
Yes it's exactly was I meant.
I'd like to find a way to restore the store state while querying for new results.

Your solution looks good, otherwise the only solution would be to fire an action to clean the store, before fetching new data.

Honestly I don't think we have other solution without polluting the one way data flow.

**Comment by subpopular** [comment]
Not sure if this applies in your particular scenario, but I've started using this pattern (from the flummox demo) in my handler views:

```` javascript
statics: {
    async routerWillRun(state, flux) {
      let itemActionIds = flux.getActions('item');
      return itemActions.getItems();
    }
  }
```

And the main snippet:

``` javascript
Router.run(routes, function (Handler, state) {
  async function run() {
    await performRouteHandlerStaticMethod(state.routes, 'routerWillRun', state, flux);
    React.withContext(
      { flux },
      () => React.render(<Handler />, document.getElementById('app'))
    );
  }
  run().catch(error => {
    throw error;
  });
}); 
```

And the `performRouteHandlerStaticMethod` function:

``` javascript
async function performRouteHandlerStaticMethod(routes, methodName, ...args) {
  return Promise.all(routes
    .map(route => route.handler[methodName])
    .filter(method => typeof method === 'function')
    .map(method => method(...args))
  );
}
```

Coming from Angular, this is essentially the same as resolving some data before instantiating the next controller. In some cases I use this to make sure the new data has arrived before rendering the next route's view. In other cases, when I don't want the delay or I'm not actually changing routes, I have had to implement an additional action to explicitly empty certain objects in my state. 

I'm pretty new to Flux in general so I may be telling you what you already know.
