### ISSUE TITLE
Optimistic updates in Flummox

### ISSUE THREAD

**Issue by cyberthom** [acdlite/flummox#215]
The docs mention that there's a "one-to-one relationship between constants and actions".

This isn't necessarily true for use cases such as optimistic updates. How do you see something like the below Flux action creator handled in Flummox?

TodoActionCreators.js
```
function removeTodo(id) {
    // Used for optimistic updates
    Dispatcher.dispatch({
        actionType: ActionTypes.TODO_REMOVE,
        id: id
    });

    asyncRemoveFromServer(id)
        .then(() => {
            Dispatcher.dispatch({
                actionType: ActionTypes.TODO_REMOVE_DONE,
                id: id
            });
        })
        .catch((error) => {
            // Used to revert optimistic updates
            Dispatcher.dispatch({
                actionType: ActionTypes.TODO_REMOVE_FAIL,
                id: id,
                error: error
            });
        });
}
```

**Comment by johanneslumpe** [comment]
The equivalent of this in flummox would be:

```
class YourActionCreator extends Actions {
  async removeTodo(id) {
    return await asyncRemoveFromServer(id);
  }
}
```

In you store you can then register using `registerAsync` and specify a handler for begin, success and failure. Flummox will automatically dispatch the appropriate actions for you. All handlers will receive the original payload used to trigger the action initially, so you can know which id as affected in case of an error. Does that help you?

**Comment by cyberthom** [comment]
Awesome. I didn't know about the `registerAsync(actionId, beginHandler, successHandler, failureHandler)` method. Exactly what I needed!

**Comment by johanneslumpe** [comment]
Perfect :)
