### ISSUE TITLE
Don't pass flux as parameter to render prop of FluxComponent

### ISSUE THREAD

**Issue by acdlite** [acdlite/flummox#216]
Right now in the master branch, `render` is called like so:

```js
render(storeState, actions, flux)
```

However, now that action injection is merged in, there's no reason under normal circumstances for flux to be exposed. You can always use `contextTypes` and `context` directly if needed.

Instead, the third param should be the hash of props passed directly to FluxComponent, excepting those that are part of the FluxComponent interface. These used to be mixed into the first argument, but even though they've been separated, they're still needed.

**Comment by johanneslumpe** [comment]
Let's get this in to 4.0 :+1:
