### ISSUE TITLE
What is the idiomatic approach to make AJAX requests

### ISSUE THREAD

**Issue by moroshko** [acdlite/flummox#218]
Imagine an autosuggest component which needs to perform an AJAX request on every key press.

Currently, my AJAX call sits inside the component itself:

```js
import xhr from 'xhr';

export default class MyComponent extends React.Component {
  getSuggestions(input, callback) {
    xhr({ uri: 'http://my-endpoint' }, function(error, response) {
      callback(null, JSON.parse(response.body));
    });
  }
  render() {
    return (
      <Autosuggest suggestions={this.getSuggestions.bind(this)} />
    );
  }
}
```

If feel like the AJAX call shouldn't be inside `MyComponent`, but in action instead.

Do you have any examples of using flummox with AJAX requests?

**Comment by johanneslumpe** [comment]
You  will probably want to move your request into an action and then have a store pick up your new data, which then flows back into your autosuggest component as props. You will make use of `connectToStores` to have your store state automatically injected via props into your component.

And your `getSuggestions` method will most likely then look like this:

```javascript
getSuggestions(input) {
  this.props.flux.getActions('autosuggest').getSuggestions(input);
}
```

Inside the `async` action you will have an then trigger your request through your api layer/object and return `await`ed result. Inside your store, use `this.register` or `this.registerAsync` to listen to dispatches from those actions.

After changing all that, the `render` method of your component will be like this:

```javascript
render() {
    return (
      // use the props here which you are injecting, I just assume you'll name it `suggestions`
      <Autosuggest suggestions={this.props.suggestions} />
    );
  }
```

Can you work with this?

**Comment by moroshko** [comment]
@johanneslumpe Yep. Thanks a lot!

It would be nice to see a complete AJAX example in the docs one day ;)
