### ISSUE TITLE
Updated Store passes un-updated props to Component

### ISSUE THREAD

**Issue by alexfedoseev** [acdlite/flummox#219]
I created sample app to illustrate two issues: this one and #195.
Sample app: https://github.com/alexfedoseev/flummox-cuts (clone repo && `npm install`&& `npm start`)

**Use case**
I have Post Store with 3 posts. Each item in this Store has tags:

Post 1: `["javascript", "flux"]`
Post 2: `["javascript", "react"]`
Post 3: `["react"]`

In my views I can list all the posts or filter them by tag. Two top level components `PostsHandler` and `TagsHandler` are prefetching posts by static method and passing them to shared `Post Component` with layout.

```
-> `/`
   |-- PostsHandler Component (Flummox Component, prefetching all posts)
       |-- Post Component
-> `/tags/:tag`
   |-- TagsHandler Component (Flummox Component, prefetching posts with tag)
       |-- Post Component
```
Post Components files: https://github.com/alexfedoseev/flummox-cuts/tree/master/app/bundles/app/components/Posts

When I click from list with all posts on tag `flux`, I navigate to `/tags/flux` with only `Post 1`, this is correct. But when I make second click on tag `javascript` from filtered list, I navigate to `/tags/javascript` with same `Post 1`. But Store was updated and holds `Post 1` & `Post 2`, which weren't passed to Component with props.

```javascript
/* Post Component */
componentWillReceiveProps(newProps) {
  const currentPosts = this.props.posts;
  const newPosts     = newProps.posts;

  console.log('[Posts Component] Current posts ->', currentPosts);
  // -> Post 1
  console.log('[Posts Store]     Current posts ->', this.props.flux.getStore('posts').state.posts);
  // -> Post 1
  console.log('[Posts Component] Updated posts ->', newPosts);
  // -> Post 1
  console.log('[Posts Store]     Updated posts ->', newProps.flux.getStore('posts').state.posts);
  // -> Post 1, Post 2
}
```

Why items from Store weren't passed to `Posts Component`?

Thanks for feedback!

**Comment by johanneslumpe** [comment]
The problem is simple: You are creating a new `Flummox` instance each time you have a route change on your client. This is not necessary as you only ever have one client. This is only necessary on the server-side.

If you move the instantiation out of the `router.run` callback, everything works as expected. I have submitted a pull-request to your repo :)

**Comment by alexfedoseev** [comment]
Got it! Thanks A LOT! :)
