### ISSUE TITLE
How to call actions from a view?

### ISSUE THREAD

**Issue by volkanunsal** [acdlite/flummox#221]
So I'm trying to figure out how to do certain things in Flummox I used to be able to do easily in Flux. At the top of my list is how to dispatch an action. I have tried instantiating the Action and dispatching the method on that instance, but that gives the following warning:

```
You've attempted to perform the action CalendarActions#enableDay, but it hasn't been added to a Flux instance.
```

The other alternative is to call the method on the flux object, but this doesn't feel right because the `_actions` object is marked as private in the spec. 

```
this.props.flux._actions.calendar_actions.enableDay(day)
```

What is the right approach?

**Comment by nhagen** [comment]
Lets say you have an authentication domain registered with flux that is named `user`.
```
this.flux.getActions('user').login(creds)
```
will initiate the login action on that domain.

If you haven't already, it may be immenesly helpful to go through the entire introductory documentation here: http://acdlite.github.io/flummox/docs/guides/quick-start and then here: http://acdlite.github.io/flummox/docs/guides/react-integration

This question and many others are answered on those pages, though admittedly, 'getActions' is only mentioned once in its own paragraph

``You can access a Flux instance’s actions and stores using getActions(key) and getStore(key).```

**Comment by johanneslumpe** [comment]
@nhagen's explanation is spot on. I also recommend that you check out the documentation @volkanunsal. It's a bit sparse, but it does cover the basic usage. Some stuff will change in 4.0, but for getting started it will be good if you get a general overview over the library :)

**Comment by volkanunsal** [comment]
Right on. That makes sense. I looked through the React integration guide and didn't see any mention of it. I'd suggest adding a few lines in there about this as well.

**Comment by johanneslumpe** [comment]
@volkanunsal Yeah we need to update our docs - I guess that will happen after the 4.0 release :)

**Comment by volkanunsal** [comment]
Awesome. Here is one more suggestion. Make sure to highlight that the action must return the value that the store is watching for. This caused me a very frustrating few minutes just now. My stores are hooked up to listen for actions, but the dispatcher wasn't even firing. And finally it hit me to return the value from the action handler, and suddenly it worked.

**Comment by johanneslumpe** [comment]
Yeah, there has been a discussion about this behavior. It should be made clear in the docs, what is necessary for flummox to dispatch an action for you.
