### ISSUE TITLE
How to coordinate the updates among multiple stores? 

### ISSUE THREAD

**Issue by volkanunsal** [acdlite/flummox#232]
I have a situation where I need to update two stores simultaneously, but I need one store to wait for the updates from the other store to complete before updating itself. I could do this with a `waitFor` in Flux. How can I do that in Flummox?

**Comment by johanneslumpe** [comment]
How about using [`waitFor`](https://github.com/acdlite/flummox/blob/master/src/Store.js#L160)? ;)

**Comment by volkanunsal** [comment]
Nice. Is there an example of how to do this? Do I do this in the `AppFlux` class as I create the actions and stores? 

Alternatively, do I do it when I am registering the event handlers?

**Comment by johanneslumpe** [comment]
You just do it in your handler:

```javascript
class MyStore extends Store {
  
  constructor({someActions, someStore}) {
    super();
    this.someStore = someStore;
    
    this.register(someActions.something, this.handleSomething);
  }
  
  handleSomething(body) {
    this.waitFor(this.someStore);
    
    // do stuff
  }

}
```

It is mentioned [in the store docs](http://acdlite.github.io/flummox/docs/api/store), just scroll down a bit.

**Comment by volkanunsal** [comment]
Ah, ok. My version is passing a `flux` object to the constructor. I tried using `getStore(store_id)`, but it's not finding my store. 

```javascript
  constructor(flux){
    super();
    flux.getStore('contract')
  }
```

The `_stores` property seems to be lazily bound because when I do this

```
console.log(flux._stores)
// Object {}
```

But when I print out the `flux` object, I get:

```
console.log(flux)
// AppFlux {_stores: {contract: ContractStore}}
```

**Comment by volkanunsal** [comment]
ah, never mind. I had to create the `ContractStore` earlier than the other store in `AppFlux`. It works now. Thanks for the help!

**Comment by johanneslumpe** [comment]
Haha yeah I was about to say that :) :+1:

**Comment by volkanunsal** [comment]
Just to add another note here. I had to use a `setTimeout` to make sure the action for the second store were called after the action of the first store, even though they were called in the right order. It works with that, but didn't work without it. This makes me curious if there are any known limitations to the way actions are called that makes the Dispatcher flake out.

Here is how it used to be (and the dispatch order was flubbed):

```javascript
let contractActions = this.props.flux.getActions('contract_actions');
let formActions = this.props.flux.getActions('form_actions');
// First store's action
contractActions.merge(value);
// FormStore waits for the contract store
let sectionNum = Number(this.props.params.sectionName) - 1;

// Second store's action, which waits for the first store
formActions.validateSection(sectionNum, this.props.contract);
```

And here is how it is now:

```javascript
let contractActions = this.props.flux.getActions('contract_actions');
let formActions = this.props.flux.getActions('form_actions');
// First store's action
contractActions.merge(value);

setTimeout(()=>{
  // FormStore waits for the contract store
  let sectionNum = Number(this.props.params.sectionName) - 1;
  
  // Second store's action, which waits for the first store
  formActions.validateSection(sectionNum, this.props.contract);
},0)
```

**Comment by johanneslumpe** [comment]
No that does not make sense to me. First of all: you can only wait for a store, when it also listens to the same action. If you trigger two different actions sequentially and each action is only listened to by one store, then you don't need to use `waitFor` at all, because it won't have any effect. It only works within the dispatch cycle for the same action.

**Comment by volkanunsal** [comment]
Oh, man. You're right. I think the reason I did it this way in the first place was because I couldn't think of a way to get the state of a store from another store. But now I know I can use the `flux.getStore(key)` function, and so don't need to use `waitFor` and defer the action. Haha. Super relieved!
