### ISSUE TITLE
What's missing for 4.0?

### ISSUE THREAD

**Issue by dariocravero** [acdlite/flummox#234]
Hi all,

[I wrote this a couple of days in gitter but got no answer](https://gitter.im/acdlite/flummox?at=557422bc27d2203776ccdba0) I figured this might be a better place to ask :).

It seems that [4.0](https://github.com/acdlite/flummox/milestones/4.0) is just around the corner but there are still a good few unresolved issues hanging. Could you use some help in running through them?

Also, @acdlite, by seeing your contributions to redux I can imagine that some of those ideas may make it into Flummox too which would be amazing :) Is there any roadmap ideas going forward?

EDIT: Could `4.0.0-alpha3` be released in the meantime? :)

Thanks,
Darío

**Comment by johanneslumpe** [comment]
Well as you pointed out we have the stuff tagged with the 4.0 milestone. We want to get all the stuff reading that's going to be causing breaking changes. Then we can push out the 4.0 release and do the rest in minor or patch versions. @acdlite is working on removing the action class. As soon as that's ready and we've merged the open PRs marked with 4.0 I think we will push out a release.

I think we don't need another alpha, we just need to get the version out :)

**Comment by johanneslumpe** [comment]
by the way, if you join http://www.reactiflux.com/ on slack, there is a flummox channel, which is active :)

**Comment by dariocravero** [comment]
Great! :) Thanks! BTW, as I was updating dependencies I saw `4.0.0-rc1` appear :) sweet! :dancers:
