### ISSUE TITLE
how to get a child component input value

### ISSUE THREAD

**Issue by tifa2chan** [acdlite/flummox#239]
Hi.  I'm a beginner of React and Flummox and I have a question here.
I have a form and I want to get a value from the child component and submit to Store.
How can I get the value from the child component at its parent component?  It seems that I need to write some kind of map at connectToStores, but I'm not sure.  Could you show me how to make it work?

I have codes something like below.

```javascript
class ParentComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = { };
  }

  render() {
    return (
      <form>
        <FluxComponent connectToStores={['storeA']}>
          <ChildComponent test={this.props.test}/>
        </FluxComponent>
        <input type="submit" value="Update" onClick={this.update.bind(this)} />
      </form>
    );
  }
  update(){
   // How can I get the child component value here?
  }
}


class ChildComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      test: props.test
    };
  }

  render() {
    return (
      <div>
        <input value={this.state.test} onChange={this.setTest.bind(this)}/>
      </div>
    );
  }

  setTest(e) {
    this.setState({test: e.target.value});
  }
...
}
```

**Comment by johanneslumpe** [comment]
You can pass a callback to your child component, which it calls with the new value. But this is not a flummox-related question. It might be good to ask about things like this (How can I pass a value from child component to a parent?) directly at the react repo, or better on their freenode IRC channel.

Please take a look [at the docs](https://facebook.github.io/react/tips/communicate-between-components.html) and at [this tutorial](http://facebook.github.io/react/docs/tutorial.html#callbacks-as-props).
