### ISSUE TITLE
Import flummox/component fails with 4.0.0-rc1

### ISSUE THREAD

**Issue by mikestead** [acdlite/flummox#257]
I'm having issues with `v4.0.0-rc1`. Up until this release I could  

    import FluxComponent from 'flummox/component';

as [described in the guide](http://acdlite.github.io/flummox/docs/guides/react-integration). 

Now I get the error `Cannot resolve module 'flummox/component'`.

**Comment by comnik** [comment]
I've poked around the module. It seems as if 

    import {FluxComponent} from "flummox/addons/react"

does the trick. Probably a measure to enable support for react-native.
