### ISSUE TITLE
Support for React 0.14

### ISSUE THREAD

**Issue by okonet** [acdlite/flummox#267]
I'm still on 0.3.x and wondering if the React 0.14 compat update is coming.

**Comment by pycbouh** [comment]
I second that as current version generates small yet annoying warning about ```cloneWithProps``` deprecation in FluxComponent. It would be great if before 4.0 is released we had a clean non-breaking version compatible with the latest React.

**Comment by voronianski** [comment]
@pycbouh @okonet I'm planning to add React 0.14.x support however I'm still thinking of how is it better to do this. NPM already contains Flummox 4.x rc version which makes it problematic to add latest React support to stable `3.x` version. Your thoughts?

**Comment by okonet** [comment]
Since this package does not follow semver ATM, I think it should be released as 3.x release + information about it should be added to README. What do you think?

**Comment by voronianski** [comment]
@okonet current master branch contains breaking changes of Flummox 4.x alpha version, do you propose to revert back master to the state of latest stable 3.x release, add React support here and republish it to npm as 3.x release?

**Comment by okonet** [comment]
Yes, since 0.4 was never released, React 0.14 support for it doesn't bring a lot for current users of flummox.

**Comment by okonet** [comment]
Or even create a 1.x release finally and use SemVer from there

**Comment by voronianski** [comment]
@okonet I think there are still some users that use alpha release of 4.x..

> Or even create a 1.x release finally and use SemVer from there

it's not possible :) 'cause 1.0 was already released, we can upgrade to 5.0 though it will be the same as 3.x with React support.. sounds a bit strange :)

**Comment by okonet** [comment]
Oh true, I was thinking it's still in 0.x range. Well, it seems even SemVer doesn't help to resolve such situations, or am I missing something?

**Comment by pycbouh** [comment]
@voronianski We can have a separate 3.x branch in NPM, with 4.x being stable, can't we?

**Comment by voronianski** [comment]
@pycbouh I'm not sure, need to investigate this.

**Comment by voronianski** [comment]
@pycbouh it looks like it's possible with `npm publish --tag` (https://docs.npmjs.com/cli/publish), correct me if I wrong.

**Comment by voronianski** [comment]
@okonet @pycbouh so then plan is to add React 0.14 support into 3.x version and release new stable patch as `3.6.0`, I plan to do this during weekend.

**Comment by pycbouh** [comment]
@voronianski I believe you are correct with ```npm publish --tag```. Actually, ```npm dist-tag ls flummox``` (https://docs.npmjs.com/cli/dist-tag) shows, that 4.0 rc is using another tag already.

```
latest: 3.5.2
prerelease: 4.0.0-rc1
```

Anyway, thank you!

**Comment by voronianski** [comment]
@okonet @pycbouh added in `3.6.x` version.

**Comment by Pavek** [comment]
Please list this version in [Releases](https://github.com/acdlite/flummox/releases) too. That's how many people, including me, discover new stuff. Thanks.

**Comment by voronianski** [comment]
@Pavek added, thanks

**Comment by okonet** [comment]
Cool! Thanks!
