### ISSUE TITLE
FluxComponent does not work on IE10

### ISSUE THREAD

**Issue by Pavek** [acdlite/flummox#271]
I researched the issue and it boils down to babel code implementing inheritance, which doesn't work on IE < 11. Here's the relevant links:
http://ricostacruz.com/til/babel-ie-class-inheritance.html
https://phabricator.babeljs.io/T3041

Note: it reportedly can be fixed by using some babel build options, but we have another issue here: Flummox npm module comes with *already transplied* code. I'm not sure why so, and it seems generally incorrect. Having regular source files, users of npm module would have a choice of a) how (for which browsers) to transply the code or b) use bundles in `/dist/` that are officially tested ones. 

Not sure why and if this is relevant, but bundles in '/dist/' are missed now completely (they were there before `3.6.3`).

**Comment by voronianski** [comment]
@Pavek 

> Note: it reportedly can be fixed by using some babel build options

Please share the options that can fix that babel behavior.

> Not sure why and if this is relevant, but bundles in '/dist/' are missed now completely 

`dist` folder is available now in `3.6.5`, it was missed accidentally.

> but we have another issue here: Flummox npm module comes with already transplied code. I'm not sure why so, and it seems generally incorrect. 

I's a general rule for npm modules to be shipped already transplied.

**Comment by Pavek** [comment]
>Please share the options that can fix that babel behavior.

Please see this comment: https://phabricator.babeljs.io/T3041#66105

**Comment by voronianski** [comment]
@Pavek 

that's strange that Flummox has this bug, as we're already using "loose" es5 preset - https://github.com/acdlite/flummox/blob/master/.babelrc#L3

**Comment by Pavek** [comment]
If that might help, here's the root cause as we debugged down:
In transplied `FluxComponent.js`:

```
function _inherits(subClass, superClass) {
...
 if (superClass) Object.setPrototypeOf ? 
      Object.setPrototypeOf(subClass, superClass) :
      subClass.__proto__ = superClass; }

}
```

IE10 do not support both `setPrototypeOf ` and `__proto__` thus `_inherits()` basically do not deliver what is expected to. I'm not aware of the correct way to fix this with Babel. One option was listed on first link above -- ` protoToAssign` -- but I failed to find a documentation for it because old docs of Babel are gone :(

**Comment by pycbouh** [comment]
That's not the only problem with the new version of Babel.

There's also a problem with IE8 (yeah, I know...) due to new Babel behavior. Preset ```es2015``` does not include ES3 transformations, which replace unsafe usage of reserved keywords like ```default```.

You need to have 
```js
        "plugins": [
          "transform-es3-member-expression-literals",
          "transform-es3-property-literals",
          ...
        ]
```
to fix that problem.

I would really appreciate if you added those and made Flummox 3.6 IE8-compatible.

**Comment by Pavek** [comment]
@pycbouh probably it's better to open a new bug for this to make it more track-able.

**Comment by voronianski** [comment]
@Pavek @pycbouh oh babel.. 5th version was so good :cry:

**Comment by voronianski** [comment]
I can take a closer look and experiment with plugins, presets and options a bit later, however I cannot test it 'cause I don't have IE.. maybe you have time to play with it right now?

**Comment by pycbouh** [comment]
@Pavek Ideally, it has to be a bug about Babel configuration, I think. Well, created #272 anyway.

@voronianski Yeah, this change was massive. We just moved to Babel 6, it was very tricky.

**Comment by pycbouh** [comment]
@voronianski Sure.

I can say right now, though, that we have this configuration, and it seems to work fine:

```js
      {
        "presets": ["es2015", "react"],
        "plugins": [
          "transform-es3-member-expression-literals",
          "transform-es3-property-literals",
          ["transform-es2015-classes", {"loose": true}],
          "add-module-exports",
          "transform-es2015-modules-commonjs",
          "transform-jscript"
        ]
      }
```

Note, that ```add-module-exports``` is unofficial plugin, that fixes new behavior with export. See [this](http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default).

**Comment by Pavek** [comment]
I will test now `["transform-es2015-classes", {"loose": true}]` option from the config @pycbouh kindly shared -- this one seems to be relevant for this issue.

**Comment by voronianski** [comment]
@Pavek @pycbouh thanks guys!

**Comment by Pavek** [comment]
@voronianski I'm confident that the following config fixes this issue:
```
{
	"presets": [
		"es2015-loose",
		"react",
		"stage-0"
	],
	"plugins": [["transform-es2015-classes", {"loose": true}]]
} 
```

Note: the code generated for `addons/FluxComponent.js` is different than present in `3.6.5`, so apparently `"es2015-loose"` is not *'loose-enough'* and plugins do more.

**Comment by voronianski** [comment]
@Pavek thanks, then I'll add necessary plugins to .babelrc instead of es2015 presets later today.

**Comment by pycbouh** [comment]
@voronianski I'm pretty sure ```["transform-es2015-classes", {"loose": true}]``` complements ```es2015``` preset, and not replaces it.

And please consider adding
```js
"transform-es3-member-expression-literals",
"transform-es3-property-literals"
```
for IE8 support (#272).

**Comment by voronianski** [comment]
@Pavek @pycbouh that's weird but update to `["transform-es2015-classes", {"loose": true}]` causes a lot of tests to fail.. investigating.

**Comment by Pavek** [comment]
@voronianski Any update regarding this? Thanks.

**Comment by voronianski** [comment]
@Pavek @pycbouh for now I cannot make tests pass when loose within ["transform-es2015-classes", {"loose": true}] is enabled, async/await methods on class instance are not transpiled properly.

**Comment by pycbouh** [comment]
@voronianski 
Did you keep ```es2015``` preset? It seems to [transpile async functions](http://babeljs.io/docs/plugins/transform-regenerator/), but only with [an appropriate syntax plugin](http://babeljs.io/docs/plugins/syntax-async-functions/).

Also, if you've used ```es1015-loose```, [it has settings](https://github.com/bkonkle/babel-preset-es2015-loose/blob/master/index.js#L22) to disable regenerator plugin from creating async methods when it otherwise would.

**Comment by voronianski** [comment]
@pycbouh I've checked several setups once more and after chat in Babel's Slack account I'm aware that it's a known bug in Babel that will be fixed in next version. Hopefully it will be asap.

<img width="1193" alt="2015-12-06 18 34 43" src="https://cloud.githubusercontent.com/assets/974035/11614329/14811d54-9c48-11e5-98cb-fbaa53c5b200.png">

- http://stackoverflow.com/questions/34117980/babel-v6-transform-es2015-classes-plugin-in-loose-mode-breaks-async-await-func

**Comment by voronianski** [comment]
@pycbouh @Pavek good news! new version was published several seconds ago and this bug fixed - https://github.com/babel/babel/pull/3135

**Comment by voronianski** [comment]
@Pavek @pycbouh added in `3.6.6`

**Comment by pycbouh** [comment]
Thanks!

**Comment by Pavek** [comment]
Thanks
