### ISSUE TITLE
Flummox 3.6 is incompatible with IE8

### ISSUE THREAD

**Issue by pycbouh** [acdlite/flummox#272]
As [mentioned](https://github.com/acdlite/flummox/issues/271#issuecomment-160985579) in #271, there's a problem with IE8 after Flummox switched to Babel 6.

Preset ```es2015``` does not include ES3 transformations, which replace unsafe usage of reserved keywords like ```default```.

You need to have 
```js
        "plugins": [
          "transform-es3-member-expression-literals",
          "transform-es3-property-literals",
          ...
        ]
```
to fix that problem.

I would really appreciate, if you added those and made Flummox 3.6 IE8-compatible.

**Comment by voronianski** [comment]
@pycbouh added in `3.6.6`

**Comment by pycbouh** [comment]
@voronianski 
Thanks. Problem is partially solved. However, there are some unsafe ```default``` usages left. It seems to be related to another unfixed Babel 6 problem: https://phabricator.babeljs.io/T2817

**Comment by voronianski** [comment]
@pycbouh :(
