### ISSUE TITLE
TestUtils removed from NPM

### ISSUE THREAD

**Issue by richardgregory** [acdlite/flummox#273]
Hi,

In the latest flummox version, the below files are in the .npmignore file so they aren't included in the package. Is this an oversight or intentional? My tests are failing now as I was depending on the test utils.

https://github.com/acdlite/flummox/blob/master/src/addons/TestUtils.js
https://github.com/acdlite/flummox/blob/master/test-utils.js

thanks

**Comment by voronianski** [comment]
@richardgregory I'm really sorry, they were removed accidentally, in latest version `3.6.8` they are back.

**Comment by richardgregory** [comment]
@voronianski thanks for the quick response, working now
