### ISSUE TITLE
Deprecation warning with React 15.5

### ISSUE THREAD

**Issue by lyptt** [acdlite/flummox#274]
Looks like React.PropTypes is deprecated, which means when using FluxComponent you get the following deprecation warning:

```
Warning: Accessing PropTypes via the main React package is deprecated.
Use the prop-types package from npm instead.
```

More info here: https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by ai** [comment]
@voronianski can we release small patch release to fix this version?

I understand that project is not in active development, but we still have several Flummox components and will not be able to migrate to Logux in next few months.

I can send you PR if you need it.
