### ISSUE TITLE
FluxMixin props change

### ISSUE THREAD

**Issue by quazzie** [acdlite/flummox#29]
If i have FluxMixin and i use a prop in the connectToStore thingie it does not fetch new data on prop change.

FluxMixin({
  MyStore: function(store) { return { items: store.getItems(this.props.itemIds) }; }
})

if i pass new prop itemIds this.state.items does not get updated.

**Comment by acdlite** [comment]
Great find, will fix ASAP

**Comment by quazzie** [comment]
Great! 
Btw very nice work!
I've been trying them all and i must say i think this is the cleanest and best way to flux!

**Comment by acdlite** [comment]
Thanks! :)
