### ISSUE TITLE
FluxComponent loop and dependant store access

### ISSUE THREAD

**Issue by quazzie** [acdlite/flummox#30]
If i want to use FluxComponent where i fetch multiple items how do i loop them ?

 ```
<FluxComponent connectToStores={{ Item: store => ({ items: store.getItems(1,2,3,4) }) }}>
  <ul>
    {??.map(item => <li key={item}>{item}></li>)}
  </ul>
</FluxComponent>
```

Do i need a component to do the mapping ?

------

If i have a FluxComponent can i access other properties?

```
<FluxComponent connectToStores={{
  Comment: store => ({ comment: store.get(this.props.commentId) }),
  User: store => ({ user: store.get(<<<<Above comment>>>.userId) })
}} />
```

**Comment by acdlite** [comment]
FluxComponent injects props into child components. So in your example, `<ul>` has an `items` prop.

> Do i need a component to do the mapping ?

Yep, exactly. The alternative is to use FluxMixin.

**Comment by acdlite** [comment]
@quazzie Sorry, I realized that I never responded to your second question! You cannot reference other props from within a store getter. However, as of 2.9.1, you can nest FluxComponents to achieve the same thing:

```js
<FluxComponent connectToStores={{
  Comment: store => ({
    comment: store.get(this.props.commentId)
  })
}}>
  <FluxComponent connectToStore={{ // has prop "comment"
    User: function(store) { // can't use arrow function because we want `this` to refer to nested component
      return {
        user: store.get(this.props.userId)
      };
    }
  }}>
    <ChildComponent /> // has props "comment" and "user"
  </FluxComponent>
</FluxComponent>
```

Hope that helps!
