### ISSUE TITLE
Extend a class that already extends Actions

### ISSUE THREAD

**Issue by subpopular** [acdlite/flummox#38]
I'm trying to set up a reusable action class that extends the flummox action class for sharing basic CRUD functionality. I'd use that to extend my action creators from as I'll be making several similar stores that need to query only slightly different data.  However, it appears that I'm unable to extend the Action class more than once. 

Here's a snippet of my crud actions:

``` javascript
class CrudActions extends Actions {

  constructor(apiRoot) {
    super();
    this.apiRoot = apiRoot
  }

  create() { 
    return {};
  }

  async save(entity = {}) {
    let url = this.apiRoot;
    let method = 'post';
    if (entity.id) {
      url += `/${entity.id}`;
      method = 'put';
    }
    return request[method](url).send(entity).exec();
  }

  async getAll(opts = {}) {
    let url = this.apiRoot + (opts.id ? `/${opts.id}`:'');
    let {body} = await request.get(url).exec();
    return body;
  }

}

```

I don't actually add this on my Flux app
And here's an example class extending from that:

``` javascript 
class PostActions extends CrudActions {
  
constructor() { 
    super('http://somedomain.com/api');
  }

  addToFavorites(post) {
    return post;
  }

}
```

Everything works as expected except when it comes to getting the actions from the Flux instance in my view:

``` javascript 
// inside a view component

this.props.flux.getActionIds('posts')
// -> returns only the ids for the PostAction's own properties, ie. addToFavorites
// It does not include inherited property names.
```

I dug around in the Actions class and it appeared to be happening around here:

``` javascript
_getActionMethodNames(instance) {
    return Object.getOwnPropertyNames(this.constructor.prototype)
      .filter(name =>
        name !== 'constructor' &&
        typeof this[name] === 'function'
      );
  }
```

I was able to set the PostAction prototype to the CrudAction prototype, but then the problem happens in reverse:

``` javascript 
// inside a view component

this.props.flux.getActionIds('posts')
// -> returns only the ids for CrudActions: save, create, getAll
// It does not include PostAction action ids
```

Now this may just be my own ignorance as I just started playing with the ES6 class syntax - but it seems I should be doing this as some sort of mixin anyhow. But how I can mixin a set of action creators and have those actions be recognized by the dispatcher when they aren't directly on my object's prototype?

There's also the possibility that I'm overcomplicating the setup and that there's a much simpler way to achieve this. 

Also, great work on this project. I love it!

**Comment by subpopular** [comment]
With Facebook's dispatcher, it dispatches to every registered store callback when it receives an action. I am correct that Flummox is slightly different in that stores only register callbacks for specific events and must explicitly do so in order to know when a dispatch occurred? 

Perhaps I'm thinking about it wrong altogether. Would it make sense to just register callbacks for all CrudActions in any interested store and then just pick out the payloads that pertain to the particular store? 

``` javascript
class ItemStore extends Store {
  constructor() {
    let crudActionIds = flux.getActionIds('crud');
    let postActionIds = flux.getActionIds('post');
    this.register(crudActionIds.getAll, this.handlePosts);
    this.register(postActionIds.addToFavorites, this.handleAddToFavorites);
  }

  handlePosts(payload) {
    if (payload.type == 'post') {
      // handle it 
    }
  }

  handleAddToFavorites() {
    // no need to check for type here as I know it's for posts
  }
}
```

Of course I would need to make sure to add a type or something to the action descriptor in CrudActions...seems that'd be the 'Flux' way.

From what I've learned, the 'Flux' way tends to be the 'verbose' way : )

**Comment by acdlite** [comment]
Hi! First of all, thanks for the kind words.

> Am I correct that Flummox is slightly different in that stores only register callbacks for specific events and must explicitly do so in order to know when a dispatch occurred?

Yes, except don't think of them as events. Think of them as messages. 

> Perhaps I'm thinking about it wrong altogether. Would it make sense to just register callbacks for all CrudActions in any interested store and then just pick out the payloads that pertain to the particular store? ... Of course I would need to make sure to add a type or something to the action descriptor in CrudActions...seems that'd be the 'Flux' way.

That's exactly what `this.register(action, handler)` does for you.

Regarding your original question, having a set of base actions that you share among multiple classes misses the point of actions, I think. The purpose of an action is to initiate a dispatch. So your CrudActions class really shouldn't be an actions class. It should be an external module — most people call it something like WebAPIUtils — that you call from within your actions:

```js
import { Actions } from 'flummox';
import { getAll } from '../utils/WebAPIUtils';

class ThingActions extends Actions {
  getAllThings() {
    return getAll('/things'); // returns a promise
  }
}
```

It's the difference between *inheriting* functions and *composing* them.

Does this make sense?

**Comment by subpopular** [comment]
Hey thanks for the reply! 

To clarify, my CrudActions class is only trying to provide common action creators to it's subclasses - I do use a WebAPIUtils module to actually do the server communication. 

Say I'm dealing with 'widgets' and 'thingies' - both of which would have their own Actions class - 'WidgetActions' and 'ThingieActions'. Both of them may have their own specific actions, but they share the basic 'getAll' action...

``` javascript
import { Actions } from 'flummox';
import { getAll } from '../utils/WebAPIUtils';

class ThingieActions extends Actions {
  getAllItems() {
    return getAll('/thingies'); // returns a promise
  }
}

class WidgetActions extends Actions {
  getAllItems() {
    return getAll('/widgets'); // returns a promise
  }
}
```

What I was aiming for was a way to not have to define a `getAllItems` method in every Action when my things view and widget view both trigger a similar ation with a slightly different payload. My CrudActions would manage building up the message and sending the requests through my APIUtils module. 

So I guess the ultimate question is - how can get an action creator into a Flux Actions class and have it still be recognized by flux.getActionIds('thing') or flux.getActionIds('widget').

But as you say, it may just make more sense to make every store listen for CrudAction messages coming in and just weed out everything the store isn't interested in.

**Comment by acdlite** [comment]
@subpopular Hmm, I can see how having a common `getAllItems()` method could be useful, but I think `extends` is the wrong way to do achieve that. As you suggest in your original comment, I would use a mixin for this:

```js
class WidgetActions extends Actions {...}

Object.assign(WidgetActions.prototype, CrudActions.prototype);
```

**Comment by subpopular** [comment]
Brilliant! - that's what I was looking for. Thanks!

**Comment by acdlite** [comment]
Awesome!

**Comment by anatoliyarkhipov** [comment]
Why we can't just use `extends` for this, why mixins?
