### ISSUE TITLE
logging dispatched payloads

### ISSUE THREAD

**Issue by vesparny** [acdlite/flummox#42]
For debugging purpose I tried to override the Flux#dispatch method, which is just a proxy call to the original dispatcher.
Here is the method in my Flux class
```js
  dispatch(actionId, body, actionArgs) {
    console.log(actionId, body, actionArgs);
    super.dispatch.call(this, actionId, body, actionArgs);
  }
```
The problem is that the `dispatchAsync` method doesn't use the `Flux#dispatch` method but calls directly the original dispatcher one.

Is there a particular reason for that?
It would be great if everything that dispatches something, passed through the `Flux#dispatch` method. That way with a single `console.log`, we could see what's going on under the hood, with a great improvement of debugging capabilities for the whole lib.

What do you think?

**Comment by tappleby** [comment]
In my projects I've been just been registering logging directly on the dispatcher, avoids having to override any methods.

**Comment by acdlite** [comment]
I think best way to handle this would be to make the Flux class an event emitter (#10) that emits on dispatch.

**Comment by vesparny** [comment]
@tappleby Are you accessing the dispatcher? I never felt the need of doing that nor manually calling the dispatch method.
Could you post an example?

@acdlite I think you are right, this way we won't need to access internals.

**Comment by acdlite** [comment]
Dispatch event added in 2.10. About to add to docs.

**Comment by acdlite** [comment]
Done

**Comment by vesparny** [comment]
@acdlite you're suuuuuper fast!
Just integrated in my sample project, it's a great feature for seeing what's going one o in your app.
https://github.com/vesparny/flux-immutable-example/blob/master/src/Flux.js#L20

**Comment by tappleby** [comment]
@vesparny its not relevant now with the dispatch event, but I had been accessing it directly to see everything going through the dispatcher. Normally I wouldn't access the dispatcher directly but felt debug logging was an acceptable use case:

```
let flux = new Flux();
if (DEBUG) {
	flux.dispatcher.register((payload) => console.log('dispatch ->', payload));
}
```

I have also thought of using the dispatcher for analytics purposes.
