### ISSUE TITLE
issue with early propTypes warnings in react 0.13 and FluxComponent ...?

### ISSUE THREAD

**Issue by breathe** [acdlite/flummox#45]
Some changes in react v0.13 regarding late property validation

http://facebook.github.io/react/blog/2015/02/24/streamlining-react-elements.html

Am I right in thinking that these changes will mean that the current usage pattern for FluxComponent:

```
<FluxComponent connectToStores={['storeA', 'storeB']}>
  <InnerComponent />
</FluxComponent>
```

will now imply that InnerComponent is not allowed to do 'required prop' validation of any of the property values that FluxComponent will retrieve from the stores and eventually pass into the cloned InnerComponent at render time ...?  Does this mean a new pattern should be used for this ...?  Maybe passing the Component class into FluxComponent as a prop rather than a child element...?

```
<FluxComponent connectToStores={['storeA', 'storeB']} innerComponent={InnerComponent} />
```

Or maybe it would be possible to retrieve the appropriate props to pass to innerComponent at the <FluxComponent/> call site ...?

```
innerComponentProps, storeChangeSubscriptions = flux.connectFluxComponentToStores(['storeA', 'storeB']...)

<FluxComponent flux={flux} subscribeTo={storeChangeSubscriptions} >
  <InnerComponent {... innerComponentProps}/>
</FluxComponent>
```

Still very new to flux and react so apologies if I have the wrong idea in any of the above ...

**Comment by acdlite** [comment]
@breathe I'm not sure I entirely understand you mean, but as far as I can tell, prop type validation is unrelated to how FluxComponent passes props to its children.

FluxComponent relies on `cloneWithProps()`, which is still supported in React 0.13. http://facebook.github.io/react/docs/clone-with-props.html.

Here's the relevant code snippet: https://github.com/acdlite/flummox/blob/master/src/addons/FluxComponent.js#L67-L69

**Comment by breathe** [comment]
I could be wrong -- but my understanding of the blog post is that propType validation in v0.13 is going to occur at element creation time rather than at some later point during the render process.  This would mean that the usage of cloneWithProps() above will only work in this example if all the validators on InnerComponent are optional.  I believe that in previous versions of React calls to createElement succeed and prop validation occurs later so that in the example above validation would have to succeed for only the object returned by cloneWithProps().  With the earlier binding I believe property validation needs to succeed at both the <InnerComponent/> call site and the cloneWithProps() call site ...

**Comment by acdlite** [comment]
Oh, I see what you mean now. I skimmed over it, but the blog post brings up this point specifically: http://facebook.github.io/react/blog/2015/02/24/streamlining-react-elements.html#solution-early-proptype-warnings

> Note: There are valid patterns that clones a ReactElement and adds additional props to it. In that case these additional props needs to be optional.

I can see a few ways around this, each with their own pros and cons:

1. Specify props as optional. Not ideal, obviously, since having required prop validators is useful.
2. Use `getDefaultProps()`. Like (1), this works, but makes required prop validators pretty much pointless.
3. Pass default prop values directly to InnerComponent to suppress warning message. Like `getDefaultProps()`, but per instance.
4. Pass child class as prop to FluxComponent, as suggested in above comment.

(1) through (3) works already, no changes to Flummox necessary. (4) I could see adding as an option, but I want to think about this some more.

**Comment by snawbel** [comment]
Any new thoughts on this one?

**Comment by danro** [comment]
Ran into this while trying to use a required propType.

Settled on a custom render:
```js
const flux = this;

let list = flux.createStore('list', ExampleListStore, flux);
let card = flux.createStore('card', ExampleCardStore, flux);

let component = (
  <FluxComponent
    flux={flux}
    connectToStores={[
      'list',
      'card',
    ]}
    render={() => {
      return <ExampleApp
        flux={flux}
        listState={list.getImmutable()}
        cardState={card.getImmutable()}
      />;
    }}
  />
);
```
^ feels a little redundant, but it works.

**Comment by acdlite** [comment]
Yeah I'm going to go ahead and say that using the HoC is the solution.

**Comment by chadly** [comment]
I'm having trouble gleaning what the solution is in regards to the "the HoC." Google says it stands for the _House of Commons_ but I don't think sending a letter to my representative in the House of Commons will help me suppress these required prop warnings.

**Comment by johanneslumpe** [comment]
@chadly Higher order component - a method of wrapping a component inside another to provide additional functionality - kind of like a decorator.

**Comment by danro** [comment]
Also, here's an example on the docs site: http://acdlite.github.io/flummox/docs/api/higher-order-component

**Comment by chadly** [comment]
Thanks, much clearer now.
