### ISSUE TITLE
Coffeescript support

### ISSUE THREAD

**Issue by nickdima** [acdlite/flummox#47]
In the readme it says that flummox should work with coffeescript also but I have some problems with calling `super` in coffeescript classes that extend classes from flummox, it throws `Cannot call a class as a function`
Is there a compatibility issue between js generated by Babel and js generated by Coffeescript?

**Comment by acdlite** [comment]
Hmm, that's interesting. That's a new-ish part of Babel they added for ES6 spec compliance. The error occurs when you try to call a class constructor without a `new` operator.

I'm not entirely sure how CoffeeScript inheritance works, but I will investigate. Thanks for bringing this to my attention.

**Comment by acdlite** [comment]
Can you post the exact code sample that's causing the issue, please?

**Comment by nickdima** [comment]
I'm a bit confused because I don't get that error anymore (not sure why) but now it breaks in some other way. Here's the code:

```coffeescript
Flummox = require('flummox').Flummox

TrackActions = './actions/track-actions'
TrackStore = './stores/track-store'

class Flux extends Flummox

  constructor: ->
    super()
    @createActions 'tracks', TrackActions
    @createStore 'tracks', TrackStore, @

new Flux()
```

and the error:

```
TypeError: Cannot read property 'constructor' of undefined
  at getClassName (/node_modules/flummox/lib/Flux.js:278:25)
  at Flux.createActions (/node_modules/flummox/lib/Flux.js:88:27)
  at new Flux (/app/flux.coffee:10:6)
  at Object.<anonymous> (/app/flux.coffee:13:5)
  at Object.<anonymous> (/app/flux.coffee:1:1)
  at Module._compile (module.js:456:26)
```

By removing the `createActions` and `createStore` function calls it doesn't break.

**Comment by acdlite** [comment]
Judging from the stack trace, it looks like `TrackActions.prototype` is undefined. You can confirm with `console.log(typeof TrackActions.prototype)`. Are you sure TrackActions extends from the base Actions class, and that you're exporting it correctly?

**Comment by nickdima** [comment]
Oh, I think I should go to sleep :) The problem was that I wasn't calling the require function on the  actions and store but just createing some strings...

```coffeescript
TrackActions = './actions/track-actions'
TrackStore = './stores/track-store'
```

**Comment by acdlite** [comment]
Haha I skimmed right over that part! :D

I'm going to re-open this as a reminder to throw a more useful error if a non-class is passed to `createActions()` or `createStore()`

**Comment by acdlite** [comment]
Acutally never mind, I'll create a new issue
