### ISSUE TITLE
Implement re-hydration/de-hydration

### ISSUE THREAD

**Issue by acdlite** [acdlite/flummox#5]
This is biggest missing feature that will bring it up to parity with other Flux libraries, I think. Should be pretty straightforward.

- Stores will have a default #serialize() and #deserialize that converts the entire state tree to JSON.
- Store subclasses can override #serialize() and #deserialize() if they're using, say, Immutable.js data structures.

**Comment by vesparny** [comment]
How do you know where to take the state tree?
Should state be defined in some opinionated way? For instance defining the Store state in a **data** variable or something?

**Comment by acdlite** [comment]
Store state is like component state in React. Store's have a `setState()` method that should be used for all state mutations. It shallow merges new state with previous state.

For serialization, each Store should implement a `serialize()` method that will return a JSON string, and a `deserialize()` method that converts that JSON string back to state. That way, Flummox has no opinion about what kind of data structures you use, as long as you tell it how to do the conversion back and forth.

There will also be a `Flux#serialize()` method that calls `Store#serialize()` on every store and combines them into one giant JSON string using the store keys. `Flux#deserialize()` will do the opposite. If any of the stores do not implement `serialize()` / `deserialize()`, Flux will throw an error with a helpful message explaining why.

**Comment by acdlite** [comment]
To clarify my previous comment, the serialize / deserialize methods aren't required — an error is only thrown if you try to serialize without them.

**Comment by acdlite** [comment]
Implemented in #9
