### ISSUE TITLE
React Developer Tools & FluxComponent

### ISSUE THREAD

**Issue by nickdima** [acdlite/flummox#51]
It looks like FluxComponent "swallows" its children so they don't show up in the components tree. Is this a known behaviour or I'm doing something wrong?

**Comment by acdlite** [comment]
Could you post a screenshot, please?

**Comment by acdlite** [comment]
The reason I'm asking for a screenshot (or link to an example) is I can't reproduce this issue. Children show up fine for me.

**Comment by nickdima** [comment]
Sorry, I found the issue. The rendering was fine server side but client side the flux instance was missing from the context (I was ignoring the thrown error) so I was seeing the `FluxComponent`'s rendered html but not its children in dev tools.
