### ISSUE TITLE
Having a debug/development mode?

### ISSUE THREAD

**Issue by wavded** [acdlite/flummox#52]
React won't display warnings AFAIK, when you are in production mode.  Could there be a way to disable those messages in some fashion for production for Flummox?

**Comment by wavded** [comment]
Another benefit to turn that off would be removing extra noise from test suites.

**Comment by acdlite** [comment]
Yes, I've been meaning to do this. Need to wrap warnings like so

```js
if (process.env.NODE_ENV !== 'production') {
  console.warn('...');
}
```

then recommend users combine envify or webpack's DefinePlugin with a code minifier to strip in production. (Alas, this won't remove noise from test suites.)

**Comment by acdlite** [comment]
Also you don't want to strip them from test suites because there are tests to ensure that the warnings are fired

**Comment by acdlite** [comment]
Added in v2.12.2

**Comment by wavded** [comment]
rock!  thanks
