### ISSUE TITLE
`FluxComponent` error when rendering array with one element

### ISSUE THREAD

**Issue by alexanderteinum** [acdlite/flummox#53]
I’ve written a very simple todo app using flummox@^2.11.0. It starts out with with four items, and the only thing the user can do is to delete items. The component rendering the array of items fails when there is only one item left. It seems like there is an issue with `FluxComponent` – it fails when containing an array consisting of one item.

Error:

    Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined

Location:

    FluxMixin.js:189

Here is the source:

https://github.com/unfold/flummox-todo/blob/v0.1.0/entry.js

I tried to update flummox to the lastest version in order to check if it has been fixed, but it seems like I’ve got some migration to do. (It says `Uncaught TypeError: Cannot read property 'cloneWithProps' of undefined`.)

**Comment by acdlite** [comment]
Good catch. Should be fixed in v2.12.4. Thanks!

**Comment by acdlite** [comment]
@alexanderteinum Just to clarify, both of the errors you reported should be fixed.
