### ISSUE TITLE
Flummox and Coffeescript question

### ISSUE THREAD

**Issue by nambrot** [acdlite/flummox#57]
I'm trying to get Flummox to work with Coffeescript, but seem not be able to get it to do so. First, I had to manually change `require("react")` to `require("react/addons")` to make `cloneWithProps` available, but even then I still get an error at https://github.com/facebook/react/blob/master/src/utils/cloneWithProps.js#L46 saying that `child.props` is undefined. The stack trace shows this happens in FlummoxComponent's `wrapChild` function. I'm trying to run this in the browser, fyi. Do you know why this happens?

**Comment by nambrot** [comment]
My entry file is pretty straightforward:

````coffeescript
{Flux} = require('flummox/lib/Flux')
FluxComponent = require('flummox/lib/addons/FluxComponent')
flux = new Flux()

Router.run routes, Router.HistoryLocation, (Handler, state) ->

  el = <FluxComponent flux={flux}>
         <Handler params={state.params} />,
       </FluxComponent>
  React.render(el, document.getElementById("container"))

````

**Comment by acdlite** [comment]
The `react/addons` issue is a regression. Sorry about that. I will fix it promptly.

I'm not sure about the `child.props` issue, but I don't think it's specific to CoffeeScript. Do you mind posting the full stack trace so I can get a better idea of what's happening?

Also, on an unrelated note, you shouldn't require internal library files, as you are at the top of your file. There's no guarantee that the structure of the `lib` folder will not change in the future. Change it to
```js
{Flux} = require('flummox')
Fluxcomponent = require('flummox/component')
```

**Comment by acdlite** [comment]
Fixed `react/addons` issue in v2.12.5

**Comment by nambrot** [comment]
@acdlite Thanks for the so quick reply, I really appreciate it

The stack trace is posted below, sorry if the line numbers are not helpful, I havent been able to set up source maps correctly yet

![image](https://cloud.githubusercontent.com/assets/571810/6467559/ae3a69cc-c201-11e4-969b-97eec1a25613.png)

**Comment by nambrot** [comment]
So I looked a bit more, and it looks like I made it work, especially with your recommendations for the modules (still a module noob)

However, the only thing I had to do to make it work was to use `React.withContext` which seems to be deprecated with 0.13, plain `<FluxComponent flux={flux} />` did not work for me (Child component complains about flux not being set on the props)

**Comment by acdlite** [comment]
Hmm, the tests for FluxComponent are all passing, and it's working in my app. Is the source for your app available anywhere? Or if you can write a failing test case, that would be ideal.

**Comment by acdlite** [comment]
@nambrot Just noticed the errant comma on this line

```coffeescript
<Handler params={state.params} />,
```

That may have something to do with it.

**Comment by nambrot** [comment]
Removing the comma hasn't been fruitful. The app itself has been a playground for me to try things out, so I'll try to get a more isolated example up tomorrow, thanks again for the quick turnaround tho

**Comment by nambrot** [comment]
I will follow #47 and made a very obvious typing mistake by not using the `el` variable that uses the `FluxComponent`. :)

**Comment by nambrot** [comment]
What's about weird though is that the `Handler` Component has to be a `FluxComponent` itself as well, otherwise the InnerComponent does not receive the Flux instance in its props (or in its context). Does not sound right?

**Comment by acdlite** [comment]
Hmm, very weird, since the test for this is passing:

https://github.com/acdlite/flummox/blob/master/src/addons/__tests__/FluxComponent-test.js#L76-L80

**Comment by acdlite** [comment]
Thanks for continuing to dig and find the root of the problem. If you can recreate it consistently, I will fix it.

**Comment by nambrot** [comment]
Thanks for your great work, I'm really digging it!
