### ISSUE TITLE
Store Initialize function?

### ISSUE THREAD

**Issue by YourDeveloperFriend** [acdlite/flummox#58]
Is there a way to initialize data in the store via GET?

Here's a simple example of what I have to do now:

```javascript

// Question Store
import {Store} from 'flummox';
import axios from 'axios';

export default class QuestionStore extends Store {
  constructor() {
    super();
    this.initialized = false;
    this.state = {
      questions: []
    };
  }
  getQuestions() {
    if(!this.initialized) {
      this.initialized = true;
      axios.get('/api/questions').then( (questions)=> {
        this.setState({questions: questions.data.response});
      });
    }
    return this.state.questions;
  }
}

// Consuming Component

import React from 'react';
import fluxMixin from 'flummox/mixin';

let Questions = React.createClass({
  mixins: [fluxMixin({
    questions(store) { return {questions: store.getQuestions()} }
  })],
  render() {
    return (
      <div>
        <h2>Questions</h2>
        <ul>
          {this.state.questions.map(function(q) {
            return <li key={q._id}>{q.question}</li>;
          })}
        </ul>
      </div>
    );
  }
});
export default Questions;

```

I can't run the GET in `initialize` because `initialize` get's called on page load, and I don't necessarily want to fetch the data until someone consumes the data. I know some people fetch the data via Actions, but I don't agree with that method (neither do some major flux players).

I suggest implementing an `onFirstConsume` function which gets called the first time a component gets injected into the DOM that depends on that store.

```javascript

// Question Store
import {Store} from 'flummox';
import axios from 'axios';

export default class QuestionStore extends Store {
  constructor() {
    super();
    this.state = {
      questions: []
    };
  }
  onFirstConsume() {
    axios.get('/api/questions').then( (questions)=> {
      this.setState({questions: questions.data.response});
    });
  }
}

// Consuming Component

import React from 'react';
import fluxMixin from 'flummox/mixin';

let Questions = React.createClass({
  mixins: [fluxMixin(['questions'])],
  render() {
    return (
      <div>
        <h2>Questions</h2>
        <ul>
          {this.state.questions.map(function(q) {
            return <li key={q._id}>{q.question}</li>;
          })}
        </ul>
      </div>
    );
  }
});
export default Questions;
```

**Comment by acdlite** [comment]
Hi! 

Regarding your request for a new `onFirstConsume()` method... I really think this lies outside the scope of the library. The use case you described is so specific and unusual — it kinda goes against the unidirectional idea of Flux, in my view — that it would be best left to the user to implement themselves. It would be pretty easy using the `newListener` event of EventEmitters:

```js
class MyStore extends Store {
  constructor() {
    super();

    this.on('newListener', this.handleFirstConsumer);
  }

  async handleFirstConsumer(event) {
    if (event === 'change') {
      // do GET request ...
      // then remove listener
      this.removeListener('newListener', this.handleFirstConsumer);
    }
  }
}
```

Although, I must say that I really don't think this is the right approach to the problem of caching (which is essentially what you're doing, albeit in a roundabout way). Doing async in stores, especially data fetching, creates more problems than it solves, in my opinion. But you're free to disagree, of course. Honestly, Flux is pretty weak/underdeveloped in this area. Relay is going to be so sweet :)

**Comment by YourDeveloperFriend** [comment]
That `newListener` event is exactly what I'm looking for.

As for your comments about this being the right approach, I agree with what was mentioned during [React Conf](https://www.youtube.com/watch?v=LTj4O7WJJ98) where doing data fetching in the Store is a lot easier than pushing it through the actions.

I'm curious about what method you use. If you have an alternative, I'd be happy to consider it.

**Comment by acdlite** [comment]
The approach I take is to originate async data fetching inside of actions. I did watch that React Conf talk, so I'm aware that there are differing points of view. This is just the one that has made most sense to me, and seems to be most common. I'll write some docs on this eventually, but there are some good resources out there already. Here's one that @mark-bradshaw brought to my attention to earlier today: http://www.code-experience.com/async-requests-with-react-js-and-flux-revisited/

**Comment by acdlite** [comment]
Also, if you didn't know already, in Flummox you can return a promise from an Action and it'll wait for the result before dispatching, which makes things much easier.

**Comment by YourDeveloperFriend** [comment]
I liked what he said here:

> Stores pulling in data will screw you as soon as more than one Store needs to know about a data request.

But other than that, I still find his way more complicated and anti-flux in my mind. For example: In the example, he calls `getEntityDataIfNeeded` from within the component. That seems like a poor place for it, since everywhere that data was needed he'd have to duplicate that method (via a mixin or something).

Couldn't the store trigger an action anytime a request is made for data it doesn't yet contain? The action has no clue what the store contains (nor, I think, should it), but the store does, so it makes sense for the store to trigger an action requesting the data.

I'd be more tempted to follow the patterns of the larger companies in the video I showed you.

BTW, `newListener` doesn't seem to trigger at all, and I can't find it anywhere in your code. Is it an event of `EventEmitter3`?

**Comment by YourDeveloperFriend** [comment]
`newListener` was removed from [EventEmitter3](https://github.com/primus/EventEmitter3).

**Comment by YourDeveloperFriend** [comment]
So if anyone else sees this issue and wonders what I did, I overrode the `addListener` function on the store to emit `newListener`:

```
addListener(...args) {
  super.addListener(...args);
  this.emit('newListener', args[0]);
}
```

**Comment by acdlite** [comment]
Yeah, for a method like `getEntityDataIfNeeded()`, I would use some sort of helper function. Usually I have a WebAPIUtils module for stuff like that.

To me, the whole appeal of stores is that the *only* entry point for new data is via the dispatcher. If you do external data fetching from within a store, that's no longer true. Makes the flow of data harder to reason about.

(For more on this topic, I like Pete Hunt's idea of stores as a reduce + change event: https://www.youtube.com/watch?v=KtmjkCuV-EU.)

Re: `newListener`, oops, I wasn't aware that eventemitter3 didn't implement that method. Sorry about that. Good workaround, though.

**Comment by YourDeveloperFriend** [comment]
I'll watch that video in the morning, thanks!

> To me, the whole appeal of stores is that the only entry point for new data is via the dispatcher. If you do external data fetching from within a store, that's no longer true. Makes the flow of data harder to reason about.

But if you triggered an action from within a store, then all the new data is still running through the dispatcher, right?

BTW, I reached my goal tonight, server-side rendering with a flux application! I've been pushing hard on this for a few days and this was the first flux implementation that I was able to get it to work with! Thanks! :+1: :D

**Comment by acdlite** [comment]
That's awesome! Glad this library could be helpful. Just curious, which part made it easier/better for you than other Flux libraries?

**Comment by mark-bradshaw** [comment]
If I may jump in on the conversation...

I haven't used other flux libraries.  I reviewed a bunch of other ones and ended up choosing flummox for a few reasons.  It seemed to be actively worked on compared to many others.  Issues were being addressed by the author, etc.  Plus I could read through the source fairly easily.  That gave me some level of confidence in the project as a whole.  

My one "must have" for a flux library was easy isomorphic support.  I was leaning early on toward Reflux but it seemed that isomorphic was going to be an issue.  Basically the first thing I did in my project was get isomorphic server side rendering with data serializing going, and it was pretty straight forward.  Flummox FTW.  

My two gotchas so far have been finding a sane way to handle server-side pre-fetching of data, and async data load in the store (much like @YourDeveloperFriend).  I found a pattern I was happy with for server-side pre-fetch and it's been working well for me. 

 My original take on async data load was much like YDF.  I thought that it was more straightforward to have the store deal with data, rather than components.  Let the components just fire actions and not worry about what was happening with data.  I was viewing the store as having more expanded functions.  More like a data layer, than just a repository, so it would be able to initiate its own actions and handle more app logic.  I'm still not entirely sure what the best mix is, but I can see that having a simple store can be beneficial.

As my first flux app grows I'm open to learning more about flux patterns and seeing how my understanding progresses.  In the mean time I accept the wisdom of those who've been doing this for a while. :smile:

**Comment by YourDeveloperFriend** [comment]
Yeah, the main thing I was looking for was isomorphism (which is the topic I'm most fascinated about). My main goal was that I was trying to approach the problem I see in a lot of people's "Server-side rendering" apps, which was essentially:

```javascript
// On the server:
let data = DataStore.fetchNeededData();
res.render('index', React.renderToString(<RootComponent data={data} />));
```

The main problem I was seeing was that the server somehow needed to be aware of what data the Components needed in order to fetch the necessary data. I was looking for a way for the components to let the server know what data it needed (much like how Relay is going to work, I can't wait). So I was able to set up something like this:

```javascript
Router.run(routes, req.path, (Handler)=> {
  let HandlerFactory = React.createFactory(Handler);
  let flux = new Flux();
  React.renderToString(HandlerFactory({flux: flux}));
  flux.getStore('questions').removeAllListeners(); // Necessary to prevent "setState" from within flummox
  flux.flushRequests().then(function(initData) {
    res.render('index', {
      content: React.renderToString(HandlerFactory({flux: flux})),
      initData: initData
    });
  });
});
```

That way the components, on `getInitialState`, were able to fire off the internal requests, and the state was maintained such that if I called getState on the same store it would contain the populated data (after `flushRequests`). I also had to create a data structure that I could inject into the body tag (`<body data-init="<%- JSON.stringify(initData); %>">`), that would initialize the stores with the data once the bootstrap code ran (otherwise it would clobber the html as soon as the bootstrap ran and request the data again).

I tried a few others I tried:

`reflux` - The use of singletons required wrapping everything in functions in order to create a factory that would return an instance (rather than a singleton). Too much boilerplate, although I really like the way they think of actions.
`fluxxor` - I didn't like the use of constants to manage the listening to actions. I may have given up on it too easily though since I was still trying to figure out flux.

I was working on creating an extensible way to do  what I described and I as went down the paths of both those other two frameworks I was finding that 1) I was writing too much boilerplate and 2) to satisfy the requirements of the isomorphic server-side rendering, I would have to really fight their system. Other than this issue, I haven't hit a single roadblock, and I can already see the mixin I'd need to create to make it extremely accessible.

**Comment by mark-bradshaw** [comment]
I also wanted to figure out how to make that sort of thing work.  I liked the Relay model of having components know about their data needs, but how to make that work with flummox.  My approach is similar.  It looked like this (flummox + react router):

```
Router.run(routes, request.path, (Handler, state) => {

    prepopulateData(flux, state, () => {

        let markup = React.renderToStaticMarkup(<Handler />);		
        var data = flux.serialize();
				
        // send markup + data to browser...
        });
});
```

My prepopulate function looks like this:

```
Async.each(state.routes, (route, aECallback) => {

        // react 0.12
	if (route.handler.type.prototype.prepopulateData) {
		return route.handler.type.prototype.prepopulateData(flux, state, aECallback);
	}
		
	// This is for the react 0.13
	// if (route.handler.prototype.prepopulateData) {
	// 	return route.handler.prototype.prepopulateData(flux, state, aECallback);
	// }

	return aECallback();
}, callback);
```

Then each component just adds a function called `prepopulate` if it wants to do any data preloading in the stores.

What I liked about the approach was that the routing didn't need to know anything about what stores needed to be pre-loaded for which routes.  The components determined what data they needed for each route and fired the necessary actions to get that data.  When they got it, they called the callback to signal readiness.

**Comment by breathe** [comment]
Your prepopulate function looks quite similar in intent to the performRouteHandlerStaticMethod function within the flummox-isomorphic-demo -- https://github.com/acdlite/flummox-isomorphic-demo/blob/master/src/shared/performRouteHandlerStaticMethod.js

**Comment by mark-bradshaw** [comment]
Yes. Very similar. Callbacks instead of promises but same general idea.
