### ISSUE TITLE
Can't get Flux context work

### ISSUE THREAD

**Issue by ivan-kleshnin** [acdlite/flummox#61]
```javascript
/// flux.js ==========================
export default class Flux extends Flummox {
  ...
}

// app.js ============================
let Flux = require("./flux.js");
let flux = new Flux();
...
window.router.run(function(Handler, state) {
  React.withContext(
    { flux }, () => React.render(<Handler />, document.body)
  );
});

// some-component.js  ================
...
  contextTypes: {
    flux: React.PropTypes.instanceOf(Flummox),
  },

  render() {
    console.log(this.context.flux); // Flux {dispatcher: Dispatcher...}
    console.log(this.context.flux instanceof Flummox); // true, right type
    return (
      <FluxComponent>
        <div>Root</div>
      </FluxComponent>
    );
```

**Warning: Invalid context `flux` supplied to `FluxComponent`, expected instance of `Flux`. Check the render method of `SomeComponent`.**

**fluxMixin.js:62 Uncaught Error: fluxMixin: Could not find Flux instance. Ensure that your component has either `this.context.flux` or `this.props.flux`.**

---
What's wrong? Also tried with `<FluxComponent flux={this.context.flux}>`. Same error.

**Comment by acdlite** [comment]
Hmm, hard to diagnose from just that snippet. Looks fine to me. Are you sure the Flummox class in your snippet above is the actual base Flummox class? It could be you forgot to use `extends`.

**Comment by ivan-kleshnin** [comment]
No, as 
```
console.log(this.context.flux instanceof require("flummox").Flummox);
```
logs true, class is ok. Also tried with `React.PropTypes.any` but that does not affect.

**Comment by acdlite** [comment]
Yeah a failing test case would be ideal. Thanks.

**Comment by acdlite** [comment]
Here's the current test we have for this, which is passing: https://github.com/acdlite/flummox/blob/master/src/addons/__tests__/FluxComponent-test.js#L42-L56

**Comment by ivan-kleshnin** [comment]
This is somehow connected with browserify. I continue to search.

**Comment by ivan-kleshnin** [comment]
May it be that if `flummox` is in "vendors.js" separate bundle – this happens. 
My experiments lead to this conclusion.

**Comment by acdlite** [comment]
Ah, I see. Is FluxComponent in the "vendors.js" as well bundle? It's an addon, so it's not required when you do `require('flummox')` — you need to do `require('flummox/component')` separately. That might fix ix. Not that familiar dealing with multiple browserify bundles, just a hunch.

**Comment by ivan-kleshnin** [comment]
Yep, confirmed. Browserify bites again :(
I included "flummox" to "vendors.js" and excluded from "app.js". 
But "flummox/component" still somehow landed in "app.js". 
When I explicitly defined "flummox/component" along with "flummox" – issues disappeared.
I don't know how this happend and why. I don't really want to know, just another anti-browserify story...

**Comment by acdlite** [comment]
Glad you figured it out! I may need to add some clarification to the docs in case others have this problem.

**Comment by ivan-kleshnin** [comment]
Thanks! They can find it by search or google at least. That's something.

**Comment by ivan-kleshnin** [comment]
Btw, my code does not work without explicit `contextType` though I saw you mentioned somewhere it's not required.

```javascript
contextTypes: {
    flux: React.PropTypes.any,
}
```

**Comment by acdlite** [comment]
Which part doesn't work? You'll still need contextType if you want to do `this.context.flux`. It's not required for components which implement fluxMixin (which includes FluxComponent). Does that make sense?

**Comment by ivan-kleshnin** [comment]
> You'll still need contextType if you want to do this.context.flux
Yes, that's exactly how it is. I only thinked about mentioning this in docs, mostly because context is undocumented feature of react.

**Comment by acdlite** [comment]
Yep, I see how that could be confusing.

**Comment by fczuardi** [comment]
Thanks for this thread! I was having the same problem with flummox in a browserify bundle and flummox/component in another, including both on my vendors.js and excluding them from app.js fixed it :)

**Comment by okonet** [comment]
I have a similar issue with webpack and CommonsChunkPlugin. Solved by explicitly passing `flux` via props:

```
render() {
        return (
            <FluxComponent flux={this.props.flux} connectToStores={['DashboardStore']}>
                <DashboardIndex/>
            </FluxComponent>
        );
    }
```

**Comment by revolunet** [comment]
Hello

i think this issue should be reopened; something is weird when packaging with browserify. if you export flummox in a separate bundle, you get confusing errors in the browser : "fluxMixin: Could not find Flux instance. Ensure that your component has either this.context.flux or this.props.flux."

adding flummox to a separate bundle and then we get some weirds error with missing dependencies. Looks like there's a packaging issue

does anyone has a working splitted browserify bundle including flummox ?

**Comment by btipling** [comment]
This problem is the worst. It wasn't really apparent that it was a flummox causing a problem until I reduced the code to just FluxComponent. Sometimes I got the error message in problem description, sometimes I got a different one, just happened that I searched the wrong one first. 

**Just make sure that if you create a vendor.js that you include both flummox and flummox/component in it.**
