### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by ivan-kleshnin** [acdlite/flummox#62]
I have an action like this:
```javascript
async loadMany() {
  let response;
  response = await Axios.get(`/api/robotz/`); // wrong URL to produce error 
  return List(response.data);
}
```

and a store connection line like this:
```javascript
this.registerAsync(actionIds.loadMany, undefined, this.loadManyCompleted, this.loadManyFailed);
```

As promise rejects (API returns 404), `this.loadManyFailed` handler is called **but** I get a message `Unhandled promise rejection`. How can it be unhandled if handler is called? 

If I wrap AJAX request in `try/catch`, error is gone, but I cannot reach `this.loadManyFailed` anymore.
As I understand, this fail handler is meant exactly for API errors (must not catch syntax errors, etc). 
Where is my error?

**Comment by acdlite** [comment]
You're not doing anything wrong. This happens is because when you return a rejected promise to an action handler, not only is the error the dispatched, but the rejected promise is returned to the caller as well. So even though the error is being handled by the stores, there's still an unhandled promise rejection — the one returned to the caller.  I realize this is a bit confusing, but the caller needs to be able to know the operation has failed.

**Comment by ivan-kleshnin** [comment]
But this logs like error in console :confused: Do you mean it will have zero consequences on following code evaluation just like basic 404 request? I'm not sure because I have little experience with promises.

**Comment by ivan-kleshnin** [comment]
I suspect rejected promise somehow breaks the code. Look at the example of optimistic removal:
```javascript
  removeBegin(id) {
    this.setState({
      cache: this.state.models.set(id, this.state.models.get(id)),
      models: this.state.models.delete(id)
    });
  }

  removeCompleted(id) {
    this.setState({
      cache: this.state.cache.delete(id),
    });
  }

  removeFailed(response) {
    let id = response.config.id;
    this.setState({
      models: this.state.models.set(id, this.state.cache.get(id)), // *
      cache: this.state.cache.delete(id),
    });
  }
```

Line, marked `*` has no effect. State is correct, but component does not refresh.

**Comment by gaearon** [comment]
The only consequence is whatever lines following this `await` in the calling code will *not* be executed unless you wrap `await` call into a try-catch. No other problems.

**Comment by acdlite** [comment]
Yep, this will only affect evaluation if you `await` the rejected promise inside an async function, which is akin to throwing an error. The remaining lines of the async function will not be executed.

**Comment by gaearon** [comment]
This doesn't feel quite right though. And it sits with what I said re: not liking implicit async return value for actions. Caller doesn't always care what happens next, and the fact that stores may have handled the error makes it semantically wrong to treat it as unobserved.

I guess it might have been better if caller could specify she wants fire-and-forget async behavior and *opt into* getting promise returned. Is this possible with current API?

**Comment by acdlite** [comment]
For fire-and-forget behavior, you can just not await the function.

**Comment by gaearon** [comment]
But the promise will still be reported unobserved, wouldn't it? It would be created, it would fail, and no one would handle failure.

If there was a way to avoid creating it in the first place.,

**Comment by gaearon** [comment]
Imagine something like `await actions.doSomething().promise` where promise is a lazily created getter.
This is probably too "clever", not sure.

**Comment by acdlite** [comment]
Yeah, it would still log to the console, but it wouldn't affect evaluation in any way.

I'm not keen to mess with the simplicity of actions returning their return value. In the general case, you want the promise to be returned so you the caller can decide whether it should continue or stop evaluation.

What you could do is write a helper that calls a promise-returning function and "handles" the error. Under the hood it would basically do a try-catch:

```js
// written in ES5 because Flummox doesn't use async-await,
// so that it doesn't depend on regenerator.
function fireAndForget(asyncFunction) {
  return asyncFunction().catch(err => {
    // do nothing, or maybe return an info object
  });
}

// inside your view/caller
await fireAndForget(asyncFunction); // will never throw or reject
```

I could see adding this even though it's not really specific to Flummox itself.

**Comment by acdlite** [comment]
Also re:

> the fact that stores may have handled the error makes it semantically wrong to treat it as unobserved

One way promises are different from synchronous code is that you can attach multiple handlers to a single promise, essentially "forking" them. That's why this feels weird, but it's consistent with how promises work.

**Comment by acdlite** [comment]
Just want to emphasize again that Flummox isn't doing anything special with the return value. It's sending the *exact return value* back to the caller. To mess with that is to mess with the basics of how functions work, in my view.

The only special thing that's happening is that the return value is *also* being dispatched.

**Comment by ivan-kleshnin** [comment]
@gaearon, @acdlite thanks. @gaearon, you used word "caller" multiple times which is obscure to me.
Could you elaborate this term? What do you mean by "caller"?

**Comment by gaearon** [comment]
Method that calls an action.

**Comment by acdlite** [comment]
Yep. I simplified the source code here to make it a bit clearer what's actually going on under the hood.

https://github.com/acdlite/flummox/blob/master/src/Actions.js#L51-L63

**Comment by ivan-kleshnin** [comment]
Ok, as a verdict, it can be caught and muted (HTTP exceptions) at `this.props.flux.getActions("robots").loadMany();` time (action call)
if I want to (HTTP exceptions). Phew, those dispatcher stuff feels really involved.
