### ISSUE TITLE
with react@0.13.0-rc2 cloneElement is replacing cloneWithProps

### ISSUE THREAD

**Issue by jeffbski** [acdlite/flummox#64]
I was just reading up on react@0.13.0-rc2 and wanted to mention that `cloneWithProps` used by your FluxComponent will likely want to switch to `cloneElement`. `cloneWithProps` will be deprecated.

http://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html#react.cloneelement

It also looks like cloneElement will handle refs better than cloneWithProps did.

**Comment by acdlite** [comment]
Yep, I saw this, too. Planning to cut a major release soon after 0.13, where this will be changed. Thanks!

**Comment by acdlite** [comment]
Fixed

**Comment by Industrial** [comment]
Looks like there was one left :-)
