### ISSUE TITLE
What does complete independence mean?

### ISSUE THREAD

**Issue by pe3** [acdlite/flummox#76]
I have tried Flummox in the browser and I like it a lot. Now I'm wondering if I could develop actions and stores in the terminal without all the browser stuff. But how to do it? I'm reading from [Flummox README](https://github.com/acdlite/flummox#modular) that Store, Actions, and Flux are completely independent from each other.

Then I'm trying:
```
//file: github-followers.js
import { Actions } from 'flummox';
import request from 'superagent';

export default class StargazerActions extends Actions {

  async getStargazersByRepo(owner, repo) {
    let response = await request
      .get(`https://api.github.com/repos/${owner}/${repo}/stargazers`)
      .query({
        per_page: 50,
      })
      .exec();

    return {
      owner,
      repo,
      stargazers: response.body,
    };
  }

}

let a = new StargazerActions();

console.log(a.getStargazersByRepo("acdlite", "flummox"));
```
I run: `babel-node -r github-followers.js`. I get: `You've attempted to perform the asynchronous action StargazerActions#getStargazersByRepo, but it hasn't been added to a Flux instance.`

So I'm wondering if I have misunderstood what independence means or is it that the README is unclear? In any case. How should I rewrite this to be able to run it in the terminal? How could I test just a store in the terminal?

**Comment by acdlite** [comment]
It's just a warning, yes? Or is it throwing an error? It used to throw an error but as of v2.12.2 it should just warn.

In a future update, I think I'll just remove the warning. Not sure how helpful it really is.

**Comment by acdlite** [comment]
Oh and the final line needs to be wrapped in either a Promise handler or an async function like so:

```js
a.getStargazersByRepo("acdlite", "flummox").then(result => console.log(result));

// or
async function() {
  let result = a.getStargazersByRepo("acdlite", "flummox");
  console.log(result);
}()
```

**Comment by pe3** [comment]
Thanks. It's just a warning. Would it be possible to show it only in the browser?

Thanks for the help but I still can't get the code to display any reults:
```
import { Actions } from 'flummox';
import request from 'superagent';

export default class StargazerActions extends Actions {

  async getStargazersByRepo(owner, repo) {
    let response = await request
      .get(`https://api.github.com/repos/${owner}/${repo}/stargazers`)
      .query({
        per_page: 50,
      })
      .exec();
    return {
      owner,
      repo,
      stargazers: response.body,
    };
  }

}

let a = new StargazerActions();
a.getStargazersByRepo("acdlite", "flummox").then(result => console.log(result));
``` 

The code is from [your demo](https://github.com/acdlite/flummox-isomorphic-demo/blob/master/src/shared/actions/StargazerActions.js). What is that `.exec();` Is it Superagent, ES6 or ES7? This oldstyle superagent code would output the results for me:
```
var request = require('superagent');
function getStargazersByRepo(owner, repo){
	var url = 'https://api.github.com/repos/'+owner+'/'+repo+'/stargazers'; 
	request
	.get(url)
		.query({
			per_page: 50,
		})
		.end(function(err, res){
			if (res.ok) {
				console.log(JSON.stringify(res.body));
			} else {
				console.log(res.text);
			}
		});
}
getStargazersByRepo("acdlite", "flummox");
```

**Comment by acdlite** [comment]
`.exec()` is just a monkey-patch I added to promisify it. https://github.com/acdlite/flummox-isomorphic-demo/blob/master/src/shared/init.js#L12-L21 In my current project I'm using GitHub's fetch polyfill instead, which is nicer.

Hmm, I'm not sure why it's not working... Does the promise ever resolve? Maybe node is exiting before it gets a chance to resolve? Have you tried from a test runner with async-support like mocha?

**Comment by acdlite** [comment]
Oh... duh. There's no monkey patch if you're running this file only. :)

**Comment by acdlite** [comment]
I'm going to close this for now. If you're still having problems let me know.
