### ISSUE TITLE
Store complains about external .setState() 

### ISSUE THREAD

**Issue by ivan-kleshnin** [acdlite/flummox#80]
If `setTimeout` is used. 

```javascript
# Store 
...
loadManyCompleted(models) {
  setTimeout(function() {
    this.setState({
      ...
    });
  }.bind(this), 2000);
}
...
```

Bug or feature? At least text may be rewritten to account this case, imo.

**Comment by aaronshaf** [comment]
I'd want to be able to externally setState on stores in my tests.

**Comment by acdlite** [comment]
It's there to warn you against a) calling `setState()` from outside the store, and b) doing async inside the store, which should be handled in actions.

But it's just a warning. Won't affect code execution. If too many more people complain about this, though, I may just get rid of it. It's only meant to be helpful.

**Comment by aaronshaf** [comment]
> "it's just a warning

When one is running thousands of tests, polluting the output is a huge annoyance.

**Comment by acdlite** [comment]
Yeah I hear ya. What about some sort of environment variable check that would silence warnings? Like `process.env.NODE_ENV === 'test'` or similar.

**Comment by aaronshaf** [comment]
Sometimes we run tests against other environments. :-\

There are good use-cases (particularly testing) for externally running setState. I would just describe it as an anti-pattern in the docs.

**Comment by acdlite** [comment]
Yeah, I think you're right. I'll remove from next release. Kind of a bummer, because I know from feedback that's it's been helpful to some people.
