### ISSUE TITLE
Make flux more restrictive?

### ISSUE THREAD

**Issue by ivan-kleshnin** [acdlite/flummox#81]
Why `flux.getActions("ssdsd")` returns `undefined` instead of throwing?

**Comment by acdlite** [comment]
Get operations in JS don't normally throw if there's nothing there. Think about `Map.get()` or `object['nonExistentKey']`.

**Comment by ivan-kleshnin** [comment]
Well, yes, but should we really follow the behaviour of native data here? They have generic behavior cause they are...generic. Otherwise, unexisting action is obviously an error which should be notified as soon as possible IMO.

**Comment by acdlite** [comment]
I guess it's just personal preference, but it seems unnecessary to me. What if you wanted to check to see if some actions existed? Then you'd have to do a try/catch just for a simple existence check. I think this way is more in line with what you'd expect in JavaScript.

**Comment by ivan-kleshnin** [comment]
Ok, I think if people will get such errors massively they will complain here. Let's close for now.
