### ISSUE TITLE
Cannot dispatch in the middle of a dispatch

### ISSUE THREAD

**Issue by ivan-kleshnin** [acdlite/flummox#82]
Store can't invoke new actions from action handlers. Reflux allowed this.

```javascript
// Store
loadManyFailed(response) {
  let alertActions = this.flux.getActions("alerts");
  this.setState({
    loaded: true,
  })
  alertActions.add(`Failed to load ${response.url}`, "error"); // throws
}
```

**Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch**

This, theoretically, may be solved by reversing dependencies and making Alert actions dependent of all other actions but I'd prefer to keep system Alerts pure and unconcerned of all other stuff.

**Comment by anderslemke** [comment]
I ran into a similar problem. I'm guessing it should not be solved like I did: using `setTimeout`.

In my case, I have a Store that handles pubsub (Faye) channels subscribed to by the app.

I want a mechanism to let all stores know, that the pubsub-connection is established (or lost).

So, I thought it would make sense to dispatch an action when the connection was established. A store listening to that action, would have to fetch some data, which, as I understand, should be done in an Action creator.

So, an action dispatch, leads to potentially several other dispatchs from different stores.

Is this the wrong way to go about this?

**Comment by acdlite** [comment]
Stores triggering actions is an anti-pattern. If you want to fire an action as a result of another action, do it inside the action handler.

```js
await someAction() {
  let result = await fetchSomething();
  this.anotherAction(); // fire another action
  return result;
}
```

**Comment by acdlite** [comment]
Generally, you want to keep any async stuff out of your stores. See https://github.com/acdlite/flummox/issues/55 for more discussion.

**Comment by ivan-kleshnin** [comment]
> Stores triggering actions is an anti-pattern. If you want to fire an action as a result of another action, do it inside the action handler

I agree this is an anti-pattern. To fire an action on fail I have no choice except to add try/catch, right?

**Comment by acdlite** [comment]
Yes, or a promise handler.
