### ISSUE TITLE
this.constructor.assignState can be undefined

### ISSUE THREAD

**Issue by ivw** [acdlite/flummox#83]
It might not be safe to call static methods on `this.constructor`, because it doesn't work with all transpilers, like TypeScript, where it breaks every Store subclass even if they don't try to override assignState.

Using `Store.assignState` instead of `this.constructor.assignState` fixes this, but of course this won't let it be overridden.

Maybe it shouldn't be static if you want it to be overridable. That would be an easy fix, but it does change the API.

**Comment by acdlite** [comment]
Hmm, not good. I'm not a TypeScript user... is it not possible to use external code without transpiling it? Could we guard against this with a conditional, and it just won't be overridable for TypeScript users? (at least until there's a better solution)

**Comment by acdlite** [comment]
Something like (pseudo-code)

```js
let assignState = isTypescript ? Store.assignState : this.constructor.assignState;
```

**Comment by ivw** [comment]
> Could we guard against this with a conditional, and it just won't be overridable for TypeScript users? (at least until there's a better solution)

Yes, this is also easy:

    (this.constructor.assignState || Store.assignState)(undefined, newState);

**Comment by acdlite** [comment]
Nice. Are you up for submitting a PR? I'm a TypeScript noob so it would probably be easier for you.

**Comment by acdlite** [comment]
If you're a TypeScript user, solution for now is to override instance method `Store#_assignState()` instead.
