### ISSUE TITLE
Upgrade guide: identical 2.x and 3.x example

### ISSUE THREAD

**Issue by jarib** [acdlite/flummox#88]
The two code examples here are identical:

![image](https://cloud.githubusercontent.com/assets/572/6648940/ef772a42-c9e0-11e4-98ab-9b8bda53cde6.png)

**Comment by acdlite** [comment]
Hahahaha I'll fix. Thanks!

**Comment by jarib** [comment]
Thanks. It would've been good as a prank. "They'll stare at this for minutes" :)
