### ISSUE TITLE
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.

### ISSUE THREAD

**Issue by nambrot** [acdlite/flummox#91]
So i'm trying to chug along my simple blog demo and am running into the following issue:

My store has 
````
  # trigger the action
  getPost: (id) ->
    post = @state.posts.get("#{id}")
    @flux.getActions('posts').fetchPost(id) unless post.get('fetched')
    post

  # subscribe to the fetch async
  fetchedPost: (post) ->
    @setState posts: @state.posts.set post.id, ImmutableJS.OrderedMap(post)
````

that the Components calls as:
````
  render: ->
    <FluxComponent connectToStores={{
      posts: (store) => post: store.getPost(@getParams().postId)
      }}>
      <Show />
    </FluxComponent>
`````

the actions is:
````
  fetchPost: (id) ->
    axios
    .get "/posts/#{id}",
      headers: {
        "Accept": "application/json"
      }
    .then (response) -> response.data
````

What ends up happening are two problems:

1. I get a `Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.`
2. I get at least 6 dispatches of the Action.

I feel like I must be doing something horribly wrong though it feels right. I probably should add another action like `fetchedPost` that the Store actually subscribes to instead of the request itself. I should also note that when I comment out the `@setState` in the action subscription in the store, I do not receive the invariant violation

**Comment by nambrot** [comment]
I'm terribly sorry, but I found out why it didn't work. During the store initial deserialization, I set the index ids as strings, where as upon the fetch I set them as integers. Another great case to just use string uuids.

**Comment by alexturek** [comment]
To anyone arriving here via search:

If you are hitting this problem, it may have something to do with kicking off a new action while an action is currently in a dispatching state. A common cause of this is kicking off an action from a function that gets called, directly or indirectly, while an Actions method is firing.

E.g.
```javascript
// In FooComponent.buttonWasClicked():
  this.flux.getActions('foo').button(data);
  // FooComponent also listens to the FooStore, though... which the 'button' action updates

// In FooComponent.componentWillUpdate(nextProps, nextState)
// Which is getting called while a store is updating, and the store is updating because
//   it's registered on the 'button' action
  this.flux.getActions('foo').doSomethingElse(); // boom
```

The way I solved this was, if I want a second action to fire as a result of some logic in the first action:
```javascript
// In FooAction.button(data):
  runSomeCode();
  if(someCondition) {
    this.doSomethingElse();
  }
```

This results in what you probably want, which is that second action being queued and dispatching _only once the first action and all its callbacks and resulting code has finished_.
